// se_game.cpp - the game-thread half. Everything UObject happens here, inside our ProcessEvent hook.
//
// HOW THE CLIENT TALKS TO THE SERVER
// ---------------------------------
// The build's own editor pawn already carries a replicated client->server RPC that takes a free-form
// string: ALevelEditorPawn::Server_AttemptLockObject(const FString& idx). We tunnel structured editor
// commands through it rather than inventing netcode:
//
//     SE|SPAWN|<class path>|<x>,<y>,<z>|<pitch>,<yaw>,<roll>
//     SE|XFORM|<handle>|<x>,<y>,<z>|<pitch>,<yaw>,<roll>|<sx>,<sy>,<sz>
//     SE|DELETE|<handle>
//     SE|QUEST|<questId>|<title>|<glyph>|<rep>|<handle:kind>,<handle:kind>,...
//
// A plain string with no "SE|" prefix is an ordinary lock request and reaches the game's own handler
// untouched, so the stock multi-user locking still works. The server-side counterpart lives in the
// HalcyonA2 payload: it hooks the same RPC, claims anything starting with "SE|", and performs the
// spawn there. Because the actor is spawned on the SERVER it replicates to every client through Iris
// with no extra work - which is exactly why the command is tunnelled instead of spawned locally.
//
// Selection uses the stock protocol unchanged: a bare handle is a real lock request, and the server
// answers with Client_SuccessfullyLockedObject / Client_FailedLock, so two people editing cannot grab
// the same actor.

#include "se_core.h"
#include "../../HalcyonA2/HalcyonA2/gamesdk/22284/SDK.hpp"
#include "MinHook.h"
#include <cmath>
#include <algorithm>
#include <cstdlib>

namespace se {
namespace {

typedef void(__fastcall* ProcessEvent_t)(void*, void*, void*);
ProcessEvent_t g_peOrig = nullptr;

SDK::UClass* g_lePawnClass = nullptr;
SDK::UClass* g_leSubsysClass = nullptr;
bool         g_paletteDirty = true;
ULONGLONG    g_lastPump = 0;

struct PendingStep { std::string handle; int kind; };
std::vector<PendingStep> g_questSteps;

bool SafePE(SDK::UObject* obj, SDK::UFunction* fn, void* parms)
{
    if (!obj || !fn || !g_peOrig) return false;
    __try { g_peOrig(obj, fn, parms); return true; }
    __except (EXCEPTION_EXECUTE_HANDLER) { Log("[game] ProcessEvent faulted on %s", "fn"); return false; }
}

// The local editor pawn, if we are in the level editor. The subsystem keeps the authoritative map of
// who is editing, so ask it rather than guessing from the object list.
SDK::UObject* FindLocalEditorPawn()
{
    if (!g_lePawnClass) g_lePawnClass = SDK::UObject::FindClassFast("LevelEditorPawn");
    if (!g_lePawnClass) return nullptr;
    const int32_t n = SDK::UObject::GObjects->Num();
    for (int32_t i = 0; i < n; ++i)
    {
        auto* o = SDK::UObject::GObjects->GetByIndex(i);
        if (!o || o->IsDefaultObject() || !o->IsA(g_lePawnClass)) continue;
        // Only the locally controlled one has a live camera + movement component wired up.
        void* cam = *reinterpret_cast<void**>(reinterpret_cast<uintptr_t>(o) + 0x3F8);  // FollowCamera
        if (cam) return o;
    }
    return nullptr;
}

// Send one tunnelled command over the stock replicated RPC.
void SendToServer(SDK::UObject* pawn, const std::string& payload)
{
    if (!pawn) { Log("[game] no editor pawn - cannot reach the server"); return; }
    auto* cls = pawn->Class;
    auto* fn = cls ? cls->GetFunction("LevelEditorPawn", "Server_AttemptLockObject") : nullptr;
    if (!fn) { Log("[game] Server_AttemptLockObject not found"); return; }

    std::wstring w(payload.begin(), payload.end());
    struct { SDK::FString idx; } parms{};
    parms.idx = SDK::FString(w.c_str());
    SafePE(pawn, fn, &parms);
}

std::string Fmt3(const Vec3& v)
{
    char b[96];
    snprintf(b, sizeof(b), "%.3f,%.3f,%.3f", v.x, v.y, v.z);
    return b;
}
std::string Fmt3(const Rot& r)
{
    char b[96];
    snprintf(b, sizeof(b), "%.3f,%.3f,%.3f", r.pitch, r.yaw, r.roll);
    return b;
}

// Discover placeable items from the game's own content rather than a hardcoded list: the LE_* prefabs
// under /Game/A2/Prefabs and /Game/A2/Progression are exactly what the shipped level editor places,
// and they already have editor icons authored under /Game/A2/LevelEditor/AutogeneratedIcons.
void BuildPalette(Snapshot& snap)
{
    const int32_t n = SDK::UObject::GObjects->Num();
    for (int32_t i = 0; i < n; ++i)
    {
        auto* o = SDK::UObject::GObjects->GetByIndex(i);
        if (!o) continue;
        const std::string name = o->GetName();
        if (name.rfind("LE_", 0) != 0) continue;            // the level-editor prefab convention
        if (name.find("_C") == std::string::npos) continue;  // want the generated classes
        const std::string full = o->GetFullName();
        std::string category = "Prefabs";
        if (full.find("/Progression/") != std::string::npos) category = "Progression";
        else if (full.find("/Quests/") != std::string::npos) category = "Quests";
        else if (full.find("/Gameplay/") != std::string::npos) category = "Gameplay";

        PaletteItem it;
        it.name = name;
        it.category = category;
        // Full name is "Class /Game/Path/Asset.Asset_C"; keep the path part for the server to load.
        const size_t sp = full.find(' ');
        it.path = (sp == std::string::npos) ? full : full.substr(sp + 1);
        snap.palette.push_back(std::move(it));
        if (snap.palette.size() >= 512) break;
    }
    std::sort(snap.palette.begin(), snap.palette.end(),
              [](const PaletteItem& a, const PaletteItem& b) {
                  if (a.category != b.category) return a.category < b.category;
                  return a.name < b.name;
              });
    Log("[game] palette: %d placeable LE item(s)", (int)snap.palette.size());
}

// Everything currently placed that the editor should be able to select. We list actors whose class is
// one of the LE prefabs, which is what this editor creates - the rest of the level is not ours to move.
void BuildObjects(Snapshot& snap)
{
    auto* actorCls = SDK::UObject::FindClassFast("Actor");
    if (!actorCls) return;
    const int32_t n = SDK::UObject::GObjects->Num();
    for (int32_t i = 0; i < n && snap.objects.size() < 1024; ++i)
    {
        auto* o = SDK::UObject::GObjects->GetByIndex(i);
        if (!o || o->IsDefaultObject() || !o->IsA(actorCls)) continue;
        auto* c = o->Class;
        if (!c) continue;
        const std::string cn = c->GetName();
        if (cn.rfind("LE_", 0) != 0) continue;

        SceneObject so;
        so.handle = o->GetName();
        so.label = so.handle;
        so.className = cn;

        // RootComponent@0x1A8 -> ComponentToWorld@0x1D0 (quat@+0, translation@+0x20, scale@+0x40)
        void* root = *reinterpret_cast<void**>(reinterpret_cast<uintptr_t>(o) + 0x1A8);
        if (root)
        {
            const double* t = reinterpret_cast<const double*>(reinterpret_cast<uintptr_t>(root) + 0x1D0 + 0x20);
            const double* s = reinterpret_cast<const double*>(reinterpret_cast<uintptr_t>(root) + 0x1D0 + 0x40);
            so.location = { t[0], t[1], t[2] };
            so.scale    = { s[0], s[1], s[2] };
        }
        snap.objects.push_back(std::move(so));
    }
}

void HandleCommands(SDK::UObject* pawn)
{
    for (const Command& c : State().Drain())
    {
        switch (c.type)
        {
        case CmdType::RefreshPalette:
            g_paletteDirty = true;
            break;

        case CmdType::SpawnItem:
            SendToServer(pawn, "SE|SPAWN|" + c.str + "|" + Fmt3(c.loc) + "|" + Fmt3(c.rot));
            Log("[game] spawn request: %s", c.str.c_str());
            break;

        case CmdType::SetTransform:
            SendToServer(pawn, "SE|XFORM|" + c.str + "|" + Fmt3(c.loc) + "|" + Fmt3(c.rot) + "|" + Fmt3(c.scale));
            break;

        case CmdType::DeleteObject:
            SendToServer(pawn, "SE|DELETE|" + c.str);
            break;

        case CmdType::SelectObject:
            // Stock protocol: a bare handle is a genuine lock request.
            SendToServer(pawn, c.str);
            break;

        case CmdType::DeselectObject:
        {
            auto* cls = pawn ? pawn->Class : nullptr;
            auto* fn = cls ? cls->GetFunction("LevelEditorPawn", "Server_UnlockObject") : nullptr;
            if (fn)
            {
                std::wstring w(c.str.begin(), c.str.end());
                struct { SDK::FString idx; } p{};
                p.idx = SDK::FString(w.c_str());
                SafePE(pawn, fn, &p);
            }
            break;
        }

        case CmdType::QuestAddStep:
            g_questSteps.push_back({ c.str, atoi(c.str2.c_str()) });
            break;

        case CmdType::QuestCompile:
        {
            std::string steps;
            for (size_t i = 0; i < g_questSteps.size(); ++i)
            {
                if (i) steps += ",";
                steps += g_questSteps[i].handle + ":" + std::to_string(g_questSteps[i].kind);
            }
            SendToServer(pawn, "SE|QUEST|" + c.str + "|" + c.str2 + "|" + steps);
            Log("[game] quest compile: %s (%d step(s))", c.str.c_str(), (int)g_questSteps.size());
            g_questSteps.clear();
            break;
        }

        case CmdType::EnterEditor:
        case CmdType::ExitEditor:
            SendToServer(pawn, c.type == CmdType::EnterEditor ? "SE|ENTER" : "SE|EXIT");
            break;
        }
    }
}

void PumpImpl()
{
    auto* pawn = FindLocalEditorPawn();

    Snapshot snap;
    // Read GWorld directly rather than SDK::UWorld::GetWorld(): that one lives in Engine_functions.cpp,
    // 5 MB of generated code we would otherwise have to compile for a single pointer load.
    const uintptr_t base = reinterpret_cast<uintptr_t>(GetModuleHandleW(nullptr));
    snap.worldReady = *reinterpret_cast<void**>(base + SDK::Offsets::GWorld) != nullptr;
    snap.inEditor = pawn != nullptr;
    if (pawn)
    {
        void* root = *reinterpret_cast<void**>(reinterpret_cast<uintptr_t>(pawn) + 0x1A8);
        if (root)
        {
            const double* t = reinterpret_cast<const double*>(reinterpret_cast<uintptr_t>(root) + 0x1D0 + 0x20);
            snap.cameraPos = { t[0], t[1], t[2] };
        }
    }

    static std::vector<PaletteItem> s_palette;
    if (g_paletteDirty && snap.worldReady)
    {
        Snapshot tmp;
        BuildPalette(tmp);
        s_palette = tmp.palette;
        g_paletteDirty = false;
    }
    snap.palette = s_palette;
    BuildObjects(snap);
    snap.status = snap.inEditor ? "editor pawn live" : (snap.worldReady ? "world ready" : "waiting for world");

    State().Publish(std::move(snap));
    HandleCommands(pawn);
}

void __fastcall PE_Hook(void* ctx, void* fn, void* parms)
{
    const ULONGLONG now = GetTickCount64();
    if (now - g_lastPump >= 250)             // 4 Hz is plenty for an editor and costs nothing
    {
        g_lastPump = now;
        static volatile long busy = 0;
        if (InterlockedCompareExchange(&busy, 1, 0) == 0)
        {
            __try { PumpImpl(); } __except (EXCEPTION_EXECUTE_HANDLER) { Log("[game] pump faulted"); }
            InterlockedExchange(&busy, 0);
        }
    }
    g_peOrig(ctx, fn, parms);
}

}  // namespace

void GameThreadPump() { PumpImpl(); }

bool InstallGameHook()
{
    const uintptr_t base = reinterpret_cast<uintptr_t>(GetModuleHandleW(nullptr));
    void* pe = reinterpret_cast<void*>(base + SDK::Offsets::ProcessEvent);
    if (MH_Initialize() != MH_OK && MH_Initialize() != MH_ERROR_ALREADY_INITIALIZED) return false;
    if (MH_CreateHook(pe, &PE_Hook, reinterpret_cast<void**>(&g_peOrig)) != MH_OK) return false;
    if (MH_EnableHook(pe) != MH_OK) return false;
    Log("[game] ProcessEvent hooked @%p", pe);
    return true;
}

}  // namespace se
