<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="MimeTypeMapOfficial" Version="1.0.17" />
    <PackageReference Include="Serilog" Version="4.0.1" />
    <PackageReference Include="Serilog.Enrichers.CallerInfo" Version="1.0.5" />
    <PackageReference Include="Serilog.Enrichers.CorrelationId" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AUnrealFeatures.DependencyInjection\AUnrealFeatures.DependencyInjection\AUnrealFeatures.DependencyInjection.csproj" />
  </ItemGroup>

</Project>
