#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AAMass

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function AAMass.AAMassAssetManager.GetAAMassAssetManager
// 0x0008 (0x0008 - 0x0000)
struct AAMassAssetManager_GetAAMassAssetManager final
{
public:
	class UAAMassAssetManager*                    ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AAMassAssetManager_GetAAMassAssetManager;

// Function AAMass.AAMassAssetManager.Load
// 0x0008 (0x0008 - 0x0000)
struct AAMassAssetManager_Load final
{
public:
	class UMassEntityConfigAsset*                 EntityConfig;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AAMassAssetManager_Load;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
