#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AAProgression

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "AAProgression_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// Class AAProgression.A2GlyphMeshComponent
// 0x0060 (0x0640 - 0x05E0)
class UA2GlyphMeshComponent final : public UStaticMeshComponent
{
public:
	class UMaterialInstanceDynamic*               DynamicMaterial;                                   // 0x05E0(0x0008)(ZeroConstructor, Transient, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_5E8[0x50];                                     // 0x05E8(0x0050)(Fixing Size After Last Property [ Dumper-7 ])
	class UA2QuestProgressComponent*              QuestProgressComponent;                            // 0x0638(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void OnLocalQuestUpdated(const struct FAARuntimeQuestState& Quest);
	void SetQuestProgressComponent(class UA2QuestProgressComponent* Component);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("A2GlyphMeshComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"A2GlyphMeshComponent")
	}
	static class UA2GlyphMeshComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UA2GlyphMeshComponent>();
	}
};
DUMPER7_ASSERTS_UA2GlyphMeshComponent;

// Class AAProgression.A2PlayerQuestComponent
// 0x00A0 (0x0148 - 0x00A8)
class UA2PlayerQuestComponent final : public UActorComponent
{
public:
	uint8                                         Pad_A8[0x58];                                      // 0x00A8(0x0058)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  ProgressionTags;                                   // 0x0100(0x0020)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnTemplate, Transient, EditConst, Protected, NativeAccessSpecifierProtected)
	struct FA2QuestProgression                    QuestProgression;                                  // 0x0120(0x0020)(Edit, Net, DisableEditOnTemplate, Transient, EditConst, RepNotify, Protected, NativeAccessSpecifierProtected)
	bool                                          IsInitialized;                                     // 0x0140(0x0001)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_141[0x7];                                      // 0x0141(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void Client_SetQuests(const struct FAAQuestBundle& FullTable, bool IsRemoving);
	void Server_ClearProgress(const struct FGuid& QuestID);
	void Server_SetProgress(const struct FGuid& QuestID, const uint8 Progress);
	void Server_SetQuestProgressionAndInitializeQuests(const struct FA2QuestProgression& Progression);
	void Server_SetQuests(const struct FAAQuestBundle& FullTable, bool IsRemoving);
	void Server_TurnInQuests(const TArray<struct FGuid>& OptionalRewardQuests);

	void OnRep_QuestProgression() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("A2PlayerQuestComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"A2PlayerQuestComponent")
	}
	static class UA2PlayerQuestComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UA2PlayerQuestComponent>();
	}
};
DUMPER7_ASSERTS_UA2PlayerQuestComponent;

// Class AAProgression.A2ProgressionStatics
// 0x0000 (0x0028 - 0x0028)
class UA2ProgressionStatics final : public UBlueprintFunctionLibrary
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("A2ProgressionStatics")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"A2ProgressionStatics")
	}
	static class UA2ProgressionStatics* GetDefaultObj()
	{
		return GetDefaultObjImpl<UA2ProgressionStatics>();
	}
};
DUMPER7_ASSERTS_UA2ProgressionStatics;

// Class AAProgression.A2QuestMasterActor
// 0x0010 (0x02A8 - 0x0298)
class AA2QuestMasterActor final : public AActor
{
public:
	uint8                                         Pad_298[0x10];                                     // 0x0298(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void TestUpdateQuestsDayRepetition();
	void TestUpdateQuestsMonthRepetition();
	void TestUpdateQuestsWeekRepetition();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("A2QuestMasterActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"A2QuestMasterActor")
	}
	static class AA2QuestMasterActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AA2QuestMasterActor>();
	}
};
DUMPER7_ASSERTS_AA2QuestMasterActor;

// Class AAProgression.A2QuestProgressComponent
// 0x0030 (0x00D8 - 0x00A8)
class UA2QuestProgressComponent final : public UActorComponent
{
public:
	TMulticastInlineDelegate<void(const struct FAARuntimeQuestState& Quest)> OnLocalQuestUpdated;    // 0x00A8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         DefaultProgress;                                   // 0x00B8(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_B9[0x3];                                       // 0x00B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   QuestName;                                         // 0x00BC(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FGuid                                  QuestID;                                           // 0x00C4(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_D4[0x4];                                       // 0x00D4(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnQuestProgressionUpdated(const struct FAAPlayerQuestInstance& QuestProgression);
	void SetQuestID(const struct FGuid& Guid);

	uint8 GetProgressOnLocalClient() const;
	uint8 GetProgressOnServerForPawn(class APawn* Pawn) const;
	void SetProgressFromLocalClient(class APawn* Pawn, const uint8 Progress) const;
	void SetProgressFromServer(class APawn* Pawn, const uint8 Progress) const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("A2QuestProgressComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"A2QuestProgressComponent")
	}
	static class UA2QuestProgressComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UA2QuestProgressComponent>();
	}
};
DUMPER7_ASSERTS_UA2QuestProgressComponent;

// Class AAProgression.ClientProgression
// 0x0440 (0x0470 - 0x0030)
class UClientProgression final : public UWorldSubsystem
{
public:
	uint8                                         Pad_30[0x230];                                     // 0x0030(0x0230)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(const struct FAAPlayerQuestInstance& QuestProgression)> OnQuestProgressionUpdated; // 0x0260(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	struct FAAPlayerQuestInstance                 QuestInstance;                                     // 0x0270(0x0170)(BlueprintVisible, BlueprintReadOnly, Transient, NativeAccessSpecifierPublic)
	uint8                                         Pad_3E0[0x10];                                     // 0x03E0(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	class UA2PlayerQuestComponent*                PlayerQuestComponent;                              // 0x03F0(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_3F8[0x28];                                     // 0x03F8(0x0028)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<struct FGuid, class UA2GlyphMeshComponent*> GlyphMeshComponents;                            // 0x0420(0x0050)(ExportObject, Transient, ContainsInstancedReference, Protected, NativeAccessSpecifierProtected)

public:
	void ClearProgress(const struct FGuid& QuestID);
	struct FAAPlayerQuestInstance GetQuestInstance();
	void SetGlyphMeshComponentColors(const struct FGuid& MasterQuestID, const struct FA2GlyphColors& Colors);
	void SetProgress(const struct FGuid& QuestID, const uint8 Progress);
	void StopQuest(const struct FGuid& QuestID, EQuestDelegateEndReason EndReason);

	bool IsQuestRunning(const struct FGuid& QuestID) const;
	void ResetQuests() const;
	void TurnInQuests() const;
	void TurnInTargetQuests(const TSet<struct FGuid>& TargetQuests) const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ClientProgression")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ClientProgression")
	}
	static class UClientProgression* GetDefaultObj()
	{
		return GetDefaultObjImpl<UClientProgression>();
	}
};
DUMPER7_ASSERTS_UClientProgression;

// Class AAProgression.QuestAssets
// 0x0050 (0x0080 - 0x0030)
class UQuestAssets final : public UDataAsset
{
public:
	TMap<class FName, class UTexture2D*>          TextureIcons;                                      // 0x0030(0x0050)(Edit, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("QuestAssets")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"QuestAssets")
	}
	static class UQuestAssets* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQuestAssets>();
	}
};
DUMPER7_ASSERTS_UQuestAssets;

// Class AAProgression.SandboxStatsLuauAPI
// 0x0000 (0x0028 - 0x0028)
class USandboxStatsLuauAPI final : public UObject
{
public:
	static void Complete(class UWorld* World, int32 PlayerId, const class FString& QuestID);
	static void Event(class UWorld* World, int32 PlayerId, const class FString& EventID);
	static void EventNumber(class UWorld* World, int32 PlayerId, const class FString& EventID, int32 Number);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SandboxStatsLuauAPI")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SandboxStatsLuauAPI")
	}
	static class USandboxStatsLuauAPI* GetDefaultObj()
	{
		return GetDefaultObjImpl<USandboxStatsLuauAPI>();
	}
};
DUMPER7_ASSERTS_USandboxStatsLuauAPI;

// Class AAProgression.SandboxStatsSaveGame
// 0x0060 (0x0088 - 0x0028)
class USandboxStatsSaveGame final : public USaveGame
{
public:
	struct FSandboxStatsStorage                   SandboxStatsStorage;                               // 0x0028(0x0060)(Edit, BlueprintVisible, EditConst, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SandboxStatsSaveGame")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SandboxStatsSaveGame")
	}
	static class USandboxStatsSaveGame* GetDefaultObj()
	{
		return GetDefaultObjImpl<USandboxStatsSaveGame>();
	}
};
DUMPER7_ASSERTS_USandboxStatsSaveGame;

// Class AAProgression.SandboxStatsStore
// 0x00F0 (0x0120 - 0x0030)
class USandboxStatsStore final : public UWorldSubsystem
{
public:
	uint8                                         Pad_30[0xF0];                                      // 0x0030(0x00F0)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	int32 GetStatTotal(const class FString& EventName);
	int32 GetStatTotalTimespan(const class FString& EventName, const struct FTimespan& Timespan);
	void OnEvent(int32 PlayerId, const class FString& String, int32 I);
	void SubscribeStatInstant(const class FString& EventName, TDelegate<void(int32 Value)> Event);
	void SubscribeStatTotal(const class FString& EventName, TDelegate<void(int32 Value)> Event);
	void SubscribeStatTotalTimespan(const class FString& EventName, TDelegate<void(int32 Value)> Event, const struct FTimespan& Timespan);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SandboxStatsStore")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SandboxStatsStore")
	}
	static class USandboxStatsStore* GetDefaultObj()
	{
		return GetDefaultObjImpl<USandboxStatsStore>();
	}
};
DUMPER7_ASSERTS_USandboxStatsStore;

// Class AAProgression.ServerProgression
// 0x02D8 (0x0308 - 0x0030)
class UServerProgression final : public UWorldSubsystem
{
public:
	uint8                                         Pad_30[0x230];                                     // 0x0030(0x0230)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class APawn*, class UA2PlayerQuestComponent*> PawnMapping;                                  // 0x0260(0x0050)(ExportObject, Transient, ContainsInstancedReference, NativeAccessSpecifierPublic)
	uint8                                         Pad_2B0[0x58];                                     // 0x02B0(0x0058)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ServerProgression")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ServerProgression")
	}
	static class UServerProgression* GetDefaultObj()
	{
		return GetDefaultObjImpl<UServerProgression>();
	}
};
DUMPER7_ASSERTS_UServerProgression;

// Class AAProgression.SharedProgression
// 0x0000 (0x0000 - 0x0000)
class ISharedProgression final
{
public:
	bool GetQuestDataByID(const struct FGuid& QuestID, struct FAAQuestEntry* QuestEntry);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SharedProgression")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SharedProgression")
	}
	static class ISharedProgression* GetDefaultObj()
	{
		return GetDefaultObjImpl<ISharedProgression>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_ISharedProgression;

SDK_NAMESPACE_END
