#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameStateManager

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "A2_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GameStateManager.BP_GameStateManager_C
// 0x00E0 (0x0378 - 0x0298)
class ABP_GameStateManager_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ULuauBlueprintComponent*                LuauBlueprint;                                     // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UA2SoundComponent*                      GameSoundComponent;                                // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UScoreComponent*                        ScoreComponent;                                    // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGameTimeComponent*                     GameTimeManager;                                   // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_GameSoundManager_C*                 GameSoundManager;                                  // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGameStateManagerComponent*             GameStateManager;                                  // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPrefabComponent*                       ObjectPrefab;                                      // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ULuauScriptComponent*                   LuauScript;                                        // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ABP_ArenaWall_C*                        ArenaWall;                                         // 0x02E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              GameCountdownStarting;                             // 0x02E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<class AScoreboard*>                    ScoreboardArray;                                   // 0x02F8(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	bool                                          bHasRanTestsYet;                                   // 0x0308(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_309[0x7];                                      // 0x0309(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBallSpawnerComponent*                  GamemodeBallSpawner;                               // 0x0310(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          bActivelyRunningTests;                             // 0x0318(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_319[0x7];                                      // 0x0319(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AModuleSlot*                            ModuleSlot;                                        // 0x0320(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UGoalComponent*                         GamemodeGoal;                                      // 0x0328(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         TotalTestSuccesses;                                // 0x0330(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TotalTestFailures;                                 // 0x0334(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        TimeStartedTests;                                  // 0x0338(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UBP_GameSoundManager_C*>         SoundManagersArray;                                // 0x0340(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<class ABP_SpleefBuilder_C*>            SpleefBuilders;                                    // 0x0350(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	class UStaticMeshComponent*                   ScrollingText;                                     // 0x0360(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         defaultMessage;                                    // 0x0368(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_36C[0x4];                                      // 0x036C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_JakeBallModuleSlotA_C*              JakeballModuleSlotA;                               // 0x0370(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_GameStateManager_GameStateManager_K2Node_ComponentBoundEvent_0_DelegateGetScoreboards__DelegateSignature();
	void BndEvt__BP_GameStateManager_GameStateManager_K2Node_ComponentBoundEvent_2_DelegateGameStateChanged__DelegateSignature(uint8 currentState, EStateNames StateNames);
	void BndEvt__BP_GameStateManager_GameStateManager_K2Node_ComponentBoundEvent_3_DelegateBallHitEvent__DelegateSignature(int32 EventType);
	void BndEvt__BP_GameStateManager_GameTimeManager_K2Node_ComponentBoundEvent_1_DelegateGetGameTime__DelegateSignature(double gameSeconds, double gameMinutes);
	void BndEvt__BP_GameStateManager_GameTimeManager_K2Node_ComponentBoundEvent_5_DelegateGetCountdownTime__DelegateSignature(double gameSeconds, bool gameBegun);
	void BndEvt__BP_GameStateManager_LuauBlueprint_K2Node_ComponentBoundEvent_4_BeginGamemodeDelegate__DelegateSignature();
	void BndEvt__BP_GameStateManager_ScoreComponent_K2Node_ComponentBoundEvent_6_DelegateOnScored__DelegateSignature(const struct FGoalInfo& GoalInfo);
	void ExecuteUbergraph_BP_GameStateManager(int32 EntryPoint);
	void GetSetArenaWall();
	void GetSlot(class AModuleSlot** Slot);
	void PlayClearEvent();
	void PlayEspeciallyGoodShotEvent();
	void PlaySaveEvent();
	void PlayShotEvent();
	void PlayTurnoverEvent();
	void PrintDebugString(const class FString& String, bool Success, bool FinalPrint);
	void RunGamemodeTests();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GameStateManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GameStateManager_C")
	}
	static class ABP_GameStateManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GameStateManager_C>();
	}
};
DUMPER7_ASSERTS_ABP_GameStateManager_C;

SDK_NAMESPACE_END
