#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HeartBall_small

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_HeartBall_classes.hpp"
#include "EN_PropState_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_HeartBall_small.BP_HeartBall_small_C
// 0x0020 (0x0670 - 0x0650)
class ABP_HeartBall_small_C final : public ABP_HeartBall_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_HeartBall_small_C;               // 0x0648(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        StartingScale;                                     // 0x0650(0x0008)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         IntBallTransformationType;                         // 0x0658(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DefaultRollingGravityMultiplier;                   // 0x065C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CurrentScale;                                      // 0x0660(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_HeartBall_small(int32 EntryPoint);
	void OnMovementComponentBounceOrRollOnServer(const struct FHitResult& ImpactResult, const struct FVector& ImpactVelocity);
	void OnRep_CurrentScale();
	void ReceiveBeginPlay();
	void RelayClearTransformed();
	void relayRPCInfo(class AActor* sender, class AActor* Actor, const struct FGameplayTag& TagInfo, EN_PropState StateInfo, const struct FVector& VectorInfo, const struct FVector& Vector2Info, const class FString& String, int32 Int);
	void RelayScaleChange(double NewScale);
	void ResetHeartBall();
	void TransformBallBasedOnType();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_HeartBall_small_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_HeartBall_small_C")
	}
	static class ABP_HeartBall_small_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_HeartBall_small_C>();
	}
};
DUMPER7_ASSERTS_ABP_HeartBall_small_C;

SDK_NAMESPACE_END
