#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Interactor

#include "Basic.hpp"

#include "BP_Interactor_classes.hpp"
#include "BP_Interactor_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Interactor.BP_Interactor_C.ExecuteUbergraph_BP_Interactor
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Interactor_C::ExecuteUbergraph_BP_Interactor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Interactor_C", "ExecuteUbergraph_BP_Interactor");

	Params::BP_Interactor_C_ExecuteUbergraph_BP_Interactor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Interactor.BP_Interactor_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_Interactor_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Interactor_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Interactor.BP_Interactor_C.Set Lasers Visible
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Lasers_Visible_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Interactor_C::Set_Lasers_Visible(bool Lasers_Visible_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Interactor_C", "Set Lasers Visible");

	Params::BP_Interactor_C_Set_Lasers_Visible Parms{};

	Parms.Lasers_Visible_0 = Lasers_Visible_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Interactor.BP_Interactor_C.Update Laser Visiblity
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_Interactor_C::Update_Laser_Visiblity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Interactor_C", "Update Laser Visiblity");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
