#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_JakeBallSpawner

#include "Basic.hpp"

#include "BP_JakeBallSpawner_classes.hpp"
#include "BP_JakeBallSpawner_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_JakeBallSpawner.BP_JakeBallSpawner_C.BndEvt__BP_JakeBallSpawner_BallSpawner_K2Node_ComponentBoundEvent_0_DiscWasSpawned__DelegateSignature
// (BlueprintEvent)

void ABP_JakeBallSpawner_C::BndEvt__BP_JakeBallSpawner_BallSpawner_K2Node_ComponentBoundEvent_0_DiscWasSpawned__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_JakeBallSpawner_C", "BndEvt__BP_JakeBallSpawner_BallSpawner_K2Node_ComponentBoundEvent_0_DiscWasSpawned__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_JakeBallSpawner.BP_JakeBallSpawner_C.ExecuteUbergraph_BP_JakeBallSpawner
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_JakeBallSpawner_C::ExecuteUbergraph_BP_JakeBallSpawner(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_JakeBallSpawner_C", "ExecuteUbergraph_BP_JakeBallSpawner");

	Params::BP_JakeBallSpawner_C_ExecuteUbergraph_BP_JakeBallSpawner Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
