#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LevelEditor_Pawn

#include "Basic.hpp"

#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_LevelEditor_Pawn.BP_LevelEditor_Pawn_C.ExecuteUbergraph_BP_LevelEditor_Pawn
// 0x0040 (0x0040 - 0x0000)
struct BP_LevelEditor_Pawn_C_ExecuteUbergraph_BP_LevelEditor_Pawn final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FWeightedBlendable                     K2Node_MakeStruct_WeightedBlendable;               // 0x0010(0x0010)(NoDestructor)
	TArray<struct FWeightedBlendable>             K2Node_MakeArray_Array;                            // 0x0020(0x0010)(ReferenceParm)
	struct FWeightedBlendables                    K2Node_MakeStruct_WeightedBlendables;              // 0x0030(0x0010)()
};
DUMPER7_ASSERTS_BP_LevelEditor_Pawn_C_ExecuteUbergraph_BP_LevelEditor_Pawn;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
