#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OneillGravityVolumeCylinder

#include "Basic.hpp"

#include "BP_OneillGravityVolumeBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_OneillGravityVolumeCylinder.BP_OneillGravityVolumeCylinder_C
// 0x0000 (0x03D8 - 0x03D8)
class ABP_OneillGravityVolumeCylinder_C final : public ABP_OneillGravityVolumeBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_OneillGravityVolumeCylinder_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_OneillGravityVolumeCylinder_C")
	}
	static class ABP_OneillGravityVolumeCylinder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_OneillGravityVolumeCylinder_C>();
	}
};
DUMPER7_ASSERTS_ABP_OneillGravityVolumeCylinder_C;

SDK_NAMESPACE_END
