#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerAnalytics

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "AAProgression_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_PlayerAnalytics.BP_PlayerAnalytics_C.checkForRecentlyCompleted
// 0x0060 (0x0060 - 0x0000)
struct BP_PlayerAnalytics_C_checkForRecentlyCompleted final
{
public:
	TArray<struct FGuid>                          Array;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          newlyCompleted;                                    // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGuid                                  outCompletedQuest;                                 // 0x0014(0x0010)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGuid                                  recentlyCompleted;                                 // 0x0024(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFound;                                            // 0x0034(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGuid                                  CallFunc_Array_Get_Item;                           // 0x0044(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Set_Contains_ReturnValue;                 // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_PlayerAnalytics_C_checkForRecentlyCompleted;

// Function BP_PlayerAnalytics.BP_PlayerAnalytics_C.ExecuteUbergraph_BP_PlayerAnalytics
// 0x03C8 (0x03C8 - 0x0000)
struct BP_PlayerAnalytics_C_ExecuteUbergraph_BP_PlayerAnalytics final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClientProgression*                     CallFunc_GetWorldSubsystem_ReturnValue;            // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FAAPlayerQuestInstance                 CallFunc_GetQuestInstance_ReturnValue;             // 0x0010(0x0170)()
	class UA2AnalyticsSubsystem*                  CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0180(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FAAPlayerQuestInstance                 K2Node_CustomEvent_QuestProgression;               // 0x0188(0x0170)(ConstParm)
	TDelegate<void(const struct FAAPlayerQuestInstance& QuestProgression)> K2Node_CreateDelegate_OutputDelegate; // 0x02F8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<struct FGuid>                          CallFunc_Set_ToArray_Result;                       // 0x0308(0x0010)(ReferenceParm)
	bool                                          CallFunc_HasWorldAuthority_ReturnValue;            // 0x0318(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_319[0x3];                                      // 0x0319(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x031C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0320(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_checkForRecentlyCompleted_newlyCompleted; // 0x0330(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_331[0x3];                                      // 0x0331(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGuid                                  CallFunc_checkForRecentlyCompleted_outCompletedQuest; // 0x0334(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_344[0x4];                                      // 0x0344(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_GuidToString_ReturnValue;            // 0x0348(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TMap<class FString, class FString>            K2Node_MakeMap_Map;                                // 0x0358(0x0050)(ConstParm)
	class AVRPawn*                                CallFunc_GetLocalInstance_ReturnValue;             // 0x03A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x03B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AVRPawn*                                K2Node_DynamicCast_AsVRPawn;                       // 0x03B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x03C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x03C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_PlayerAnalytics_C_ExecuteUbergraph_BP_PlayerAnalytics;

// Function BP_PlayerAnalytics.BP_PlayerAnalytics_C.OnQuestUpdate
// 0x0170 (0x0170 - 0x0000)
struct BP_PlayerAnalytics_C_OnQuestUpdate final
{
public:
	struct FAAPlayerQuestInstance                 QuestProgression;                                  // 0x0000(0x0170)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_BP_PlayerAnalytics_C_OnQuestUpdate;

// Function BP_PlayerAnalytics.BP_PlayerAnalytics_C.relayAnalytics
// 0x0068 (0x0068 - 0x0000)
struct BP_PlayerAnalytics_C_relayAnalytics final
{
public:
	class FString                                 EventName;                                         // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	TMap<class FString, class FString>            Parms_0;                                           // 0x0010(0x0050)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class UA2AnalyticsSubsystem*                  CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_PlayerAnalytics_C_relayAnalytics;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
