#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerRenderer

#include "Basic.hpp"

#include "BP_PlayerRenderer_classes.hpp"
#include "BP_PlayerRenderer_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_PlayerRenderer.BP_PlayerRenderer_C.DestroyBPComponentsOnRemotePlayers
// (Event, Public, BlueprintEvent)

void ABP_PlayerRenderer_C::DestroyBPComponentsOnRemotePlayers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerRenderer_C", "DestroyBPComponentsOnRemotePlayers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PlayerRenderer.BP_PlayerRenderer_C.EnableDisableMesh
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UStaticMeshComponent*             MeshIn                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    Enable                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USceneComponent*                  Parent                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerRenderer_C::EnableDisableMesh(class UStaticMeshComponent* MeshIn, bool Enable, class USceneComponent* Parent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerRenderer_C", "EnableDisableMesh");

	Params::BP_PlayerRenderer_C_EnableDisableMesh Parms{};

	Parms.MeshIn = MeshIn;
	Parms.Enable = Enable;
	Parms.Parent = Parent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerRenderer.BP_PlayerRenderer_C.ExecuteUbergraph_BP_PlayerRenderer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerRenderer_C::ExecuteUbergraph_BP_PlayerRenderer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerRenderer_C", "ExecuteUbergraph_BP_PlayerRenderer");

	Params::BP_PlayerRenderer_C_ExecuteUbergraph_BP_PlayerRenderer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerRenderer.BP_PlayerRenderer_C.updateMirrorVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_PlayerRenderer_C::updateMirrorVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerRenderer_C", "updateMirrorVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
