#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Speaker_LE

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Speaker_LE.BP_Speaker_LE_C
// 0x0030 (0x02C8 - 0x0298)
class ABP_Speaker_LE_C final : public AActor
{
public:
	class UPrefabComponent*                       ObjectPrefab;                                      // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ULuauBlueprintComponent*                LuaBlueprint;                                      // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ULuauScriptComponent*                   LuauScript;                                        // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             ChosenSound;                                       // 0x02B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          ChosenAkSound;                                     // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void PlaySound(const class FString& Sound_Name);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Speaker_LE_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Speaker_LE_C")
	}
	static class ABP_Speaker_LE_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Speaker_LE_C>();
	}
};
DUMPER7_ASSERTS_ABP_Speaker_LE_C;

SDK_NAMESPACE_END
