#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SmallDeathBall

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_JakeBall_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SmallDeathBall.BP_SmallDeathBall_C
// 0x0000 (0x0650 - 0x0650)
class ABP_SmallDeathBall_C final : public ABP_JakeBall_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_SmallDeathBall_C;                // 0x0648(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_SmallDeathBall(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SmallDeathBall_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SmallDeathBall_C")
	}
	static class ABP_SmallDeathBall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SmallDeathBall_C>();
	}
};
DUMPER7_ASSERTS_ABP_SmallDeathBall_C;

SDK_NAMESPACE_END
