#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TeamDisplay

#include "Basic.hpp"

#include "A2_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TeamDisplay.BP_TeamDisplay_C
// 0x0010 (0x0390 - 0x0380)
class ABP_TeamDisplay_C final : public ATeamDisplay
{
public:
	class FText                                   Value;                                             // 0x0380(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TeamDisplay_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TeamDisplay_C")
	}
	static class ABP_TeamDisplay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TeamDisplay_C>();
	}
};
DUMPER7_ASSERTS_ABP_TeamDisplay_C;

SDK_NAMESPACE_END
