#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_PlayerPawn

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "InputCore_structs.hpp"
#include "EN_PropState_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPI_PlayerPawn.BPI_PlayerPawn_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_PlayerPawn_C final
{
public:
	void getPlayerData(struct FReplicatedFrequentData* PlayerData, bool* Found);
	void getPlayerEntity(class UA2PlayerEntity** playerEntity, bool* Found);
	void GetPlayerPawn(class ABP_VRPawn_C** Pawn, bool* Found);
	void registerWithPawn(class AActor* registeringActor);
	void relayControllerInputs(EControllerHand eHand, const struct FVector2D& actionValue2D, bool actionValueBool, class UInputAction* inputActionRef, const struct FGameplayTag& Tag);
	void relayRPCInfo(class AActor* sender, class AActor* Actor, const struct FGameplayTag& TagInfo, EN_PropState StateInfo, const struct FVector& VectorInfo, const struct FVector& Vector2Info, const class FString& String, int32 Int);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_PlayerPawn_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_PlayerPawn_C")
	}
	static class IBPI_PlayerPawn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_PlayerPawn_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_PlayerPawn_C;

SDK_NAMESPACE_END
