#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_PlayerPawn

#include "Basic.hpp"

#include "BPI_PlayerPawn_classes.hpp"
#include "BPI_PlayerPawn_parameters.hpp"


SDK_NAMESPACE_START

// Function BPI_PlayerPawn.BPI_PlayerPawn_C.getPlayerData
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FReplicatedFrequentData*         PlayerData                                             (Parm, OutParm, NoDestructor)
// bool*                                   Found                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_PlayerPawn_C::getPlayerData(struct FReplicatedFrequentData* PlayerData, bool* Found)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_PlayerPawn_C", "getPlayerData");

	Params::BPI_PlayerPawn_C_getPlayerData Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (PlayerData != nullptr)
		*PlayerData = std::move(Parms.PlayerData);

	if (Found != nullptr)
		*Found = Parms.Found;
}


// Function BPI_PlayerPawn.BPI_PlayerPawn_C.getPlayerEntity
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UA2PlayerEntity**                 playerEntity                                           (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool*                                   Found                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_PlayerPawn_C::getPlayerEntity(class UA2PlayerEntity** playerEntity, bool* Found)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_PlayerPawn_C", "getPlayerEntity");

	Params::BPI_PlayerPawn_C_getPlayerEntity Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (playerEntity != nullptr)
		*playerEntity = Parms.playerEntity;

	if (Found != nullptr)
		*Found = Parms.Found;
}


// Function BPI_PlayerPawn.BPI_PlayerPawn_C.GetPlayerPawn
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_VRPawn_C**                    Pawn                                                   (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   Found                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_PlayerPawn_C::GetPlayerPawn(class ABP_VRPawn_C** Pawn, bool* Found)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_PlayerPawn_C", "GetPlayerPawn");

	Params::BPI_PlayerPawn_C_GetPlayerPawn Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Pawn != nullptr)
		*Pawn = Parms.Pawn;

	if (Found != nullptr)
		*Found = Parms.Found;
}


// Function BPI_PlayerPawn.BPI_PlayerPawn_C.registerWithPawn
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           registeringActor                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void IBPI_PlayerPawn_C::registerWithPawn(class AActor* registeringActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_PlayerPawn_C", "registerWithPawn");

	Params::BPI_PlayerPawn_C_registerWithPawn Parms{};

	Parms.registeringActor = registeringActor;

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function BPI_PlayerPawn.BPI_PlayerPawn_C.relayControllerInputs
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EControllerHand                         eHand                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 actionValue2D                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    actionValueBool                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInputAction*                     inputActionRef                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              Tag                                                    (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void IBPI_PlayerPawn_C::relayControllerInputs(EControllerHand eHand, const struct FVector2D& actionValue2D, bool actionValueBool, class UInputAction* inputActionRef, const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_PlayerPawn_C", "relayControllerInputs");

	Params::BPI_PlayerPawn_C_relayControllerInputs Parms{};

	Parms.eHand = eHand;
	Parms.actionValue2D = std::move(actionValue2D);
	Parms.actionValueBool = actionValueBool;
	Parms.inputActionRef = inputActionRef;
	Parms.Tag = std::move(Tag);

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function BPI_PlayerPawn.BPI_PlayerPawn_C.relayRPCInfo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           sender                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              TagInfo                                                (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// EN_PropState                            StateInfo                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   VectorInfo                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Vector2Info                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FString&                    String                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int32                                   Int                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_PlayerPawn_C::relayRPCInfo(class AActor* sender, class AActor* Actor, const struct FGameplayTag& TagInfo, EN_PropState StateInfo, const struct FVector& VectorInfo, const struct FVector& Vector2Info, const class FString& String, int32 Int)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_PlayerPawn_C", "relayRPCInfo");

	Params::BPI_PlayerPawn_C_relayRPCInfo Parms{};

	Parms.sender = sender;
	Parms.Actor = Actor;
	Parms.TagInfo = std::move(TagInfo);
	Parms.StateInfo = StateInfo;
	Parms.VectorInfo = std::move(VectorInfo);
	Parms.Vector2Info = std::move(Vector2Info);
	Parms.String = std::move(String);
	Parms.Int = Int;

	AsUObject()->ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
