#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EntryLevel

#include "Basic.hpp"

#include "EntryLevel_classes.hpp"
#include "EntryLevel_parameters.hpp"


SDK_NAMESPACE_START

// Function EntryLevel.EntryLevel_C.ExecuteUbergraph_EntryLevel
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEntryLevel_C::ExecuteUbergraph_EntryLevel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EntryLevel_C", "ExecuteUbergraph_EntryLevel");

	Params::EntryLevel_C_ExecuteUbergraph_EntryLevel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EntryLevel.EntryLevel_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AEntryLevel_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EntryLevel_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
