#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LanSearchResult

#include "Basic.hpp"

#include "LanSearchResult_classes.hpp"
#include "LanSearchResult_parameters.hpp"


SDK_NAMESPACE_START

SDK_NAMESPACE_END
