#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LE_BP_VFX_TackleBallGoal01a

#include "Basic.hpp"

#include "LE_BP_VFX_TackleBallGoal01a_classes.hpp"
#include "LE_BP_VFX_TackleBallGoal01a_parameters.hpp"


SDK_NAMESPACE_START

// Function LE_BP_VFX_TackleBallGoal01a.LE_BP_VFX_TackleBallGoal01a_C.BndEvt__LE_BP_VFX_TackleBallGoal01a_TeamBased_K2Node_ComponentBoundEvent_2_BlueprintAction__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const struct FLinearColor&              Primary                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FLinearColor&              Secondary                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALE_BP_VFX_TackleBallGoal01a_C::BndEvt__LE_BP_VFX_TackleBallGoal01a_TeamBased_K2Node_ComponentBoundEvent_2_BlueprintAction__DelegateSignature(const struct FLinearColor& Primary, const struct FLinearColor& Secondary)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LE_BP_VFX_TackleBallGoal01a_C", "BndEvt__LE_BP_VFX_TackleBallGoal01a_TeamBased_K2Node_ComponentBoundEvent_2_BlueprintAction__DelegateSignature");

	Params::LE_BP_VFX_TackleBallGoal01a_C_BndEvt__LE_BP_VFX_TackleBallGoal01a_TeamBased_K2Node_ComponentBoundEvent_2_BlueprintAction__DelegateSignature Parms{};

	Parms.Primary = std::move(Primary);
	Parms.Secondary = std::move(Secondary);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LE_BP_VFX_TackleBallGoal01a.LE_BP_VFX_TackleBallGoal01a_C.BndEvt__LE_BP_VFX_TackleBallGoal01a_Toggleable_K2Node_ComponentBoundEvent_0_BlueprintAction__DelegateSignature
// (BlueprintEvent)

void ALE_BP_VFX_TackleBallGoal01a_C::BndEvt__LE_BP_VFX_TackleBallGoal01a_Toggleable_K2Node_ComponentBoundEvent_0_BlueprintAction__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LE_BP_VFX_TackleBallGoal01a_C", "BndEvt__LE_BP_VFX_TackleBallGoal01a_Toggleable_K2Node_ComponentBoundEvent_0_BlueprintAction__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LE_BP_VFX_TackleBallGoal01a.LE_BP_VFX_TackleBallGoal01a_C.BndEvt__LE_BP_VFX_TackleBallGoal01a_Toggleable_K2Node_ComponentBoundEvent_1_BlueprintAction__DelegateSignature
// (BlueprintEvent)

void ALE_BP_VFX_TackleBallGoal01a_C::BndEvt__LE_BP_VFX_TackleBallGoal01a_Toggleable_K2Node_ComponentBoundEvent_1_BlueprintAction__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LE_BP_VFX_TackleBallGoal01a_C", "BndEvt__LE_BP_VFX_TackleBallGoal01a_Toggleable_K2Node_ComponentBoundEvent_1_BlueprintAction__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LE_BP_VFX_TackleBallGoal01a.LE_BP_VFX_TackleBallGoal01a_C.ExecuteUbergraph_LE_BP_VFX_TackleBallGoal01a
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALE_BP_VFX_TackleBallGoal01a_C::ExecuteUbergraph_LE_BP_VFX_TackleBallGoal01a(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LE_BP_VFX_TackleBallGoal01a_C", "ExecuteUbergraph_LE_BP_VFX_TackleBallGoal01a");

	Params::LE_BP_VFX_TackleBallGoal01a_C_ExecuteUbergraph_LE_BP_VFX_TackleBallGoal01a Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LE_BP_VFX_TackleBallGoal01a.LE_BP_VFX_TackleBallGoal01a_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ALE_BP_VFX_TackleBallGoal01a_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LE_BP_VFX_TackleBallGoal01a_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
