#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OculusXRPassthrough

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "OculusXRPassthrough_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "OculusXRHMD_structs.hpp"


SDK_NAMESPACE_START

// Class OculusXRPassthrough.OculusXRPassthroughColorLut
// 0x0030 (0x0058 - 0x0028)
class UOculusXRPassthroughColorLut final : public UObject
{
public:
	EColorLutType                                 ColorLutType;                                      // 0x0028(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IgnoreAlphaChannel;                                // 0x0029(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLutTextureData                        StoredTextureData;                                 // 0x0030(0x0018)(NativeAccessSpecifierPrivate)
	uint8                                         Pad_48[0x10];                                      // 0x0048(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetLutFromArray(const TArray<struct FColor>& InColorArray, bool InIgnoreAlphaChannel);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OculusXRPassthroughColorLut")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OculusXRPassthroughColorLut")
	}
	static class UOculusXRPassthroughColorLut* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOculusXRPassthroughColorLut>();
	}
};
DUMPER7_ASSERTS_UOculusXRPassthroughColorLut;

// Class OculusXRPassthrough.OculusXRPassthroughLayerBase
// 0x0090 (0x00B8 - 0x0028)
class UOculusXRPassthroughLayerBase : public UStereoLayerShape
{
public:
	EOculusXRPassthroughLayerOrder                LayerOrder;                                        // 0x0028(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         TextureOpacityFactor;                              // 0x002C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableEdgeColor;                                  // 0x0030(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           EdgeColor;                                         // 0x0034(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableColorMap;                                   // 0x0044(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOculusXRColorMapType                         ColorMapType;                                      // 0x0045(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseColorMapCurve;                                 // 0x0046(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_47[0x1];                                       // 0x0047(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UCurveLinearColor*                      ColorMapCurve;                                     // 0x0048(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Contrast;                                          // 0x0050(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Brightness;                                        // 0x0054(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Posterize;                                         // 0x0058(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Saturation;                                        // 0x005C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LutWeight;                                         // 0x0060(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UOculusXRPassthroughColorLut*           ColorLUTSource;                                    // 0x0068(0x0008)(Edit, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UOculusXRPassthroughColorLut*           ColorLUTTarget;                                    // 0x0070(0x0008)(Edit, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           ColorScale;                                        // 0x0078(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           ColorOffset;                                       // 0x0088(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_98[0x20];                                      // 0x0098(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ClearColorMap();
	void EnableColorMap(bool bInEnableColorMap);
	void EnableColorMapCurve(bool bInEnableColorMapCurve);
	void EnableEdgeColor(bool bInEnableEdgeColor);
	void RemoveColorLut();
	void SetBrightnessContrastSaturation(float InContrast, float InBrightness, float InSaturation);
	void SetColorArray(const TArray<struct FLinearColor>& InColorArray);
	void SetColorLUTSource(class UOculusXRPassthroughColorLut* InColorLUTSource);
	void SetColorLUTTarget(class UOculusXRPassthroughColorLut* InColorLUTTarget);
	void SetColorLUTWeight(float InWeight);
	void SetColorMapControls(float InContrast, float InBrightness, float InPosterize);
	void SetColorMapCurve(class UCurveLinearColor* InColorMapCurve);
	void SetColorMapType(EOculusXRColorMapType InColorMapType);
	void SetColorScaleAndOffset(const struct FLinearColor& InColorScale, const struct FLinearColor& InColorOffset);
	void SetEdgeRenderingColor(const struct FLinearColor& InEdgeColor);
	void SetLayerPlacement(EOculusXRPassthroughLayerOrder InLayerOrder);
	void SetTextureOpacity(float InOpacity);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OculusXRPassthroughLayerBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OculusXRPassthroughLayerBase")
	}
	static class UOculusXRPassthroughLayerBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOculusXRPassthroughLayerBase>();
	}
};
DUMPER7_ASSERTS_UOculusXRPassthroughLayerBase;

// Class OculusXRPassthrough.OculusXRStereoLayerShapeReconstructed
// 0x0000 (0x00B8 - 0x00B8)
class UOculusXRStereoLayerShapeReconstructed final : public UOculusXRPassthroughLayerBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OculusXRStereoLayerShapeReconstructed")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OculusXRStereoLayerShapeReconstructed")
	}
	static class UOculusXRStereoLayerShapeReconstructed* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOculusXRStereoLayerShapeReconstructed>();
	}
};
DUMPER7_ASSERTS_UOculusXRStereoLayerShapeReconstructed;

// Class OculusXRPassthrough.OculusXRStereoLayerShapeUserDefined
// 0x0010 (0x00C8 - 0x00B8)
class UOculusXRStereoLayerShapeUserDefined final : public UOculusXRPassthroughLayerBase
{
public:
	uint8                                         Pad_B8[0x10];                                      // 0x00B8(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OculusXRStereoLayerShapeUserDefined")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OculusXRStereoLayerShapeUserDefined")
	}
	static class UOculusXRStereoLayerShapeUserDefined* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOculusXRStereoLayerShapeUserDefined>();
	}
};
DUMPER7_ASSERTS_UOculusXRStereoLayerShapeUserDefined;

// Class OculusXRPassthrough.OculusXRPassthroughLayerComponent
// 0x0050 (0x0420 - 0x03D0)
class UOculusXRPassthroughLayerComponent final : public UStereoLayerComponent
{
public:
	TMap<class FString, class UMeshComponent*>    PassthroughComponentMap;                           // 0x03C8(0x0050)(ExportObject, Transient, ContainsInstancedReference, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_418[0x8];                                      // 0x0418(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void AddProceduralSurfaceGeometry(class UProceduralMeshComponent* ProceduralMeshComponent, bool updateTransform);
	void AddStaticSurfaceGeometry(class UStaticMeshComponent* StaticMeshComponent, bool updateTransform);
	void AddSurfaceGeometry(class AStaticMeshActor* StaticMeshActor, bool updateTransform);
	void MarkPassthroughStyleForUpdate();
	void RemoveProceduralSurfaceGeometry(class UProceduralMeshComponent* ProceduralMeshComponent);
	void RemoveStaticSurfaceGeometry(class UStaticMeshComponent* StaticMeshComponent);
	void RemoveSurfaceGeometry(class AStaticMeshActor* StaticMeshActor);

	bool IsSurfaceGeometry(class AStaticMeshActor* StaticMeshActor) const;
	bool IsSurfaceGeometryComponent(const class UMeshComponent* MeshComponent) const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OculusXRPassthroughLayerComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OculusXRPassthroughLayerComponent")
	}
	static class UOculusXRPassthroughLayerComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOculusXRPassthroughLayerComponent>();
	}
};
DUMPER7_ASSERTS_UOculusXRPassthroughLayerComponent;

SDK_NAMESPACE_END
