#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OculusXRMovement

#include "Basic.hpp"

#include "OculusXRMovement_classes.hpp"
#include "OculusXRMovement_parameters.hpp"


SDK_NAMESPACE_START

// Function OculusXRMovement.OculusXRBodyTrackingComponent.ResetAllBoneTransforms
// (Final, Native, Public, BlueprintCallable)

void UOculusXRBodyTrackingComponent::ResetAllBoneTransforms()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRBodyTrackingComponent", "ResetAllBoneTransforms");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRMovement.OculusXREyeTrackingComponent.ClearRotationValues
// (Final, Native, Public, BlueprintCallable)

void UOculusXREyeTrackingComponent::ClearRotationValues()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXREyeTrackingComponent", "ClearRotationValues");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRMovement.OculusXRFaceTrackingComponent.ClearExpressionValues
// (Final, Native, Public, BlueprintCallable)

void UOculusXRFaceTrackingComponent::ClearExpressionValues()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRFaceTrackingComponent", "ClearExpressionValues");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRMovement.OculusXRFaceTrackingComponent.SetExpressionValue
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// EOculusXRFaceExpression                 Expression                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   Value                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRFaceTrackingComponent::SetExpressionValue(EOculusXRFaceExpression Expression, float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRFaceTrackingComponent", "SetExpressionValue");

	Params::OculusXRFaceTrackingComponent_SetExpressionValue Parms{};

	Parms.Expression = Expression;
	Parms.Value = Value;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRMovement.OculusXRFaceTrackingComponent.GetExpressionValue
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// EOculusXRFaceExpression                 Expression                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UOculusXRFaceTrackingComponent::GetExpressionValue(EOculusXRFaceExpression Expression) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRFaceTrackingComponent", "GetExpressionValue");

	Params::OculusXRFaceTrackingComponent_GetExpressionValue Parms{};

	Parms.Expression = Expression;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.IsBodyTrackingEnabled
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::IsBodyTrackingEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "IsBodyTrackingEnabled");

	Params::OculusXRMovementFunctionLibrary_IsBodyTrackingEnabled Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.IsBodyTrackingSupported
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::IsBodyTrackingSupported()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "IsBodyTrackingSupported");

	Params::OculusXRMovementFunctionLibrary_IsBodyTrackingSupported Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.IsEyeTrackingEnabled
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::IsEyeTrackingEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "IsEyeTrackingEnabled");

	Params::OculusXRMovementFunctionLibrary_IsEyeTrackingEnabled Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.IsEyeTrackingSupported
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::IsEyeTrackingSupported()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "IsEyeTrackingSupported");

	Params::OculusXRMovementFunctionLibrary_IsEyeTrackingSupported Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.IsFaceTrackingEnabled
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::IsFaceTrackingEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "IsFaceTrackingEnabled");

	Params::OculusXRMovementFunctionLibrary_IsFaceTrackingEnabled Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.IsFaceTrackingSupported
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::IsFaceTrackingSupported()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "IsFaceTrackingSupported");

	Params::OculusXRMovementFunctionLibrary_IsFaceTrackingSupported Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.RequestBodyTrackingFidelity
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// EOculusXRBodyTrackingFidelity           fidelity                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::RequestBodyTrackingFidelity(EOculusXRBodyTrackingFidelity fidelity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "RequestBodyTrackingFidelity");

	Params::OculusXRMovementFunctionLibrary_RequestBodyTrackingFidelity Parms{};

	Parms.fidelity = fidelity;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.ResetBodyTrackingCalibration
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::ResetBodyTrackingCalibration()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "ResetBodyTrackingCalibration");

	Params::OculusXRMovementFunctionLibrary_ResetBodyTrackingCalibration Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.StartBodyTracking
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::StartBodyTracking()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "StartBodyTracking");

	Params::OculusXRMovementFunctionLibrary_StartBodyTracking Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.StartBodyTrackingByJointSet
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// EOculusXRBodyJointSet                   jointSet                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::StartBodyTrackingByJointSet(EOculusXRBodyJointSet jointSet)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "StartBodyTrackingByJointSet");

	Params::OculusXRMovementFunctionLibrary_StartBodyTrackingByJointSet Parms{};

	Parms.jointSet = jointSet;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.StartEyeTracking
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::StartEyeTracking()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "StartEyeTracking");

	Params::OculusXRMovementFunctionLibrary_StartEyeTracking Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.StartFaceTracking
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::StartFaceTracking()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "StartFaceTracking");

	Params::OculusXRMovementFunctionLibrary_StartFaceTracking Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.StopBodyTracking
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::StopBodyTracking()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "StopBodyTracking");

	Params::OculusXRMovementFunctionLibrary_StopBodyTracking Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.StopEyeTracking
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::StopEyeTracking()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "StopEyeTracking");

	Params::OculusXRMovementFunctionLibrary_StopEyeTracking Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.StopFaceTracking
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::StopFaceTracking()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "StopFaceTracking");

	Params::OculusXRMovementFunctionLibrary_StopFaceTracking Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.SuggestBodyTrackingCalibrationOverride
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// float                                   Height                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::SuggestBodyTrackingCalibrationOverride(float Height)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "SuggestBodyTrackingCalibrationOverride");

	Params::OculusXRMovementFunctionLibrary_SuggestBodyTrackingCalibrationOverride Parms{};

	Parms.Height = Height;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.TryGetBodyState
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FOculusXRBodyState*              outBodyState                                           (Parm, OutParm, NativeAccessSpecifierPublic)
// float                                   WorldToMeters                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::TryGetBodyState(struct FOculusXRBodyState* outBodyState, float WorldToMeters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "TryGetBodyState");

	Params::OculusXRMovementFunctionLibrary_TryGetBodyState Parms{};

	Parms.WorldToMeters = WorldToMeters;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (outBodyState != nullptr)
		*outBodyState = std::move(Parms.outBodyState);

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.TryGetEyeGazesState
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FOculusXREyeGazesState*          outEyeGazesState                                       (Parm, OutParm, NativeAccessSpecifierPublic)
// float                                   WorldToMeters                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::TryGetEyeGazesState(struct FOculusXREyeGazesState* outEyeGazesState, float WorldToMeters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "TryGetEyeGazesState");

	Params::OculusXRMovementFunctionLibrary_TryGetEyeGazesState Parms{};

	Parms.WorldToMeters = WorldToMeters;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (outEyeGazesState != nullptr)
		*outEyeGazesState = std::move(Parms.outEyeGazesState);

	return Parms.ReturnValue;
}


// Function OculusXRMovement.OculusXRMovementFunctionLibrary.TryGetFaceState
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FOculusXRFaceState*              outFaceState                                           (Parm, OutParm, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRMovementFunctionLibrary::TryGetFaceState(struct FOculusXRFaceState* outFaceState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRMovementFunctionLibrary", "TryGetFaceState");

	Params::OculusXRMovementFunctionLibrary_TryGetFaceState Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (outFaceState != nullptr)
		*outFaceState = std::move(Parms.outFaceState);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
