#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OculusXRAnchors

#include "Basic.hpp"

#include "OculusXRAnchors_classes.hpp"
#include "OculusXRAnchors_parameters.hpp"


SDK_NAMESPACE_START

// Function OculusXRAnchors.OculusXRAnchorBPFunctionLibrary.AnchorHandleToString
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// const struct FOculusXRUInt64&           Value                                                  (ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString UOculusXRAnchorBPFunctionLibrary::AnchorHandleToString(const struct FOculusXRUInt64& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAnchorBPFunctionLibrary", "AnchorHandleToString");

	Params::OculusXRAnchorBPFunctionLibrary_AnchorHandleToString Parms{};

	Parms.Value = std::move(Value);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorBPFunctionLibrary.AnchorUUIDToString
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable, BlueprintPure)
// Parameters:
// const struct FOculusXRUUID&             Value                                                  (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString UOculusXRAnchorBPFunctionLibrary::AnchorUUIDToString(const struct FOculusXRUUID& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAnchorBPFunctionLibrary", "AnchorUUIDToString");

	Params::OculusXRAnchorBPFunctionLibrary_AnchorUUIDToString Parms{};

	Parms.Value = std::move(Value);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorBPFunctionLibrary.GetAnchorComponent
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FOculusXRSpaceQueryResult& QueryResult                                            (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
// EOculusXRSpaceComponentType             ComponentType                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          Outer_0                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class UOculusXRBaseAnchorComponent*ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

const class UOculusXRBaseAnchorComponent* UOculusXRAnchorBPFunctionLibrary::GetAnchorComponent(const struct FOculusXRSpaceQueryResult& QueryResult, EOculusXRSpaceComponentType ComponentType, class UObject* Outer_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAnchorBPFunctionLibrary", "GetAnchorComponent");

	Params::OculusXRAnchorBPFunctionLibrary_GetAnchorComponent Parms{};

	Parms.QueryResult = std::move(QueryResult);
	Parms.ComponentType = ComponentType;
	Parms.Outer_0 = Outer_0;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorBPFunctionLibrary.GetAnchorComponentStatus
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class AActor*                           TargetActor                                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EOculusXRSpaceComponentType             ComponentType                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bIsEnabled                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRAnchorBPFunctionLibrary::GetAnchorComponentStatus(class AActor* TargetActor, EOculusXRSpaceComponentType ComponentType, bool* bIsEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAnchorBPFunctionLibrary", "GetAnchorComponentStatus");

	Params::OculusXRAnchorBPFunctionLibrary_GetAnchorComponentStatus Parms{};

	Parms.TargetActor = TargetActor;
	Parms.ComponentType = ComponentType;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bIsEnabled != nullptr)
		*bIsEnabled = Parms.bIsEnabled;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorBPFunctionLibrary.GetAnchorTransformByHandle
// (Final, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FOculusXRUInt64&           Handle                                                 (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FTransform*                      OutTransform                                           (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRAnchorBPFunctionLibrary::GetAnchorTransformByHandle(const struct FOculusXRUInt64& Handle, struct FTransform* OutTransform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAnchorBPFunctionLibrary", "GetAnchorTransformByHandle");

	Params::OculusXRAnchorBPFunctionLibrary_GetAnchorTransformByHandle Parms{};

	Parms.Handle = std::move(Handle);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (OutTransform != nullptr)
		*OutTransform = std::move(Parms.OutTransform);

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorBPFunctionLibrary.GetRoomLayout
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FOculusXRUInt64&           Space                                                  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FOculusXRRoomLayout*             RoomLayoutOut                                          (Parm, OutParm, NativeAccessSpecifierPublic)
// int32                                   MaxWallsCapacity                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRAnchorBPFunctionLibrary::GetRoomLayout(const struct FOculusXRUInt64& Space, struct FOculusXRRoomLayout* RoomLayoutOut, int32 MaxWallsCapacity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAnchorBPFunctionLibrary", "GetRoomLayout");

	Params::OculusXRAnchorBPFunctionLibrary_GetRoomLayout Parms{};

	Parms.Space = std::move(Space);
	Parms.MaxWallsCapacity = MaxWallsCapacity;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (RoomLayoutOut != nullptr)
		*RoomLayoutOut = std::move(Parms.RoomLayoutOut);

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorBPFunctionLibrary.IsAnchorResultSuccess
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// EOculusXRAnchorResult                   Result                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRAnchorBPFunctionLibrary::IsAnchorResultSuccess(EOculusXRAnchorResult Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAnchorBPFunctionLibrary", "IsAnchorResultSuccess");

	Params::OculusXRAnchorBPFunctionLibrary_IsAnchorResultSuccess Parms{};

	Parms.Result = Result;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorBPFunctionLibrary.IsEqual_FOculusXRUInt64
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// const struct FOculusXRUInt64&           Left                                                   (ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FOculusXRUInt64&           Right                                                  (ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRAnchorBPFunctionLibrary::IsEqual_FOculusXRUInt64(const struct FOculusXRUInt64& Left, const struct FOculusXRUInt64& Right)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAnchorBPFunctionLibrary", "IsEqual_FOculusXRUInt64");

	Params::OculusXRAnchorBPFunctionLibrary_IsEqual_FOculusXRUInt64 Parms{};

	Parms.Left = std::move(Left);
	Parms.Right = std::move(Right);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorBPFunctionLibrary.IsEqual_FOculusXRUUID
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable, BlueprintPure)
// Parameters:
// const struct FOculusXRUUID&             Left                                                   (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FOculusXRUUID&             Right                                                  (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRAnchorBPFunctionLibrary::IsEqual_FOculusXRUUID(const struct FOculusXRUUID& Left, const struct FOculusXRUUID& Right)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAnchorBPFunctionLibrary", "IsEqual_FOculusXRUUID");

	Params::OculusXRAnchorBPFunctionLibrary_IsEqual_FOculusXRUUID Parms{};

	Parms.Left = std::move(Left);
	Parms.Right = std::move(Right);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorBPFunctionLibrary.SpawnActorWithAnchorHandle
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FOculusXRUInt64&           Handle                                                 (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FOculusXRUUID&             UUID                                                   (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EOculusXRSpaceStorageLocation           AnchorLocation                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UClass*                           ActorClass                                             (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class AActor*                           Owner                                                  (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class APawn*                            Instigator                                             (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ESpawnActorCollisionHandlingMethod      CollisionHandlingMethod                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class AActor*                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class AActor* UOculusXRAnchorBPFunctionLibrary::SpawnActorWithAnchorHandle(class UObject* WorldContextObject, const struct FOculusXRUInt64& Handle, const struct FOculusXRUUID& UUID, EOculusXRSpaceStorageLocation AnchorLocation, class UClass* ActorClass, class AActor* Owner, class APawn* Instigator, ESpawnActorCollisionHandlingMethod CollisionHandlingMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAnchorBPFunctionLibrary", "SpawnActorWithAnchorHandle");

	Params::OculusXRAnchorBPFunctionLibrary_SpawnActorWithAnchorHandle Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.Handle = std::move(Handle);
	Parms.UUID = std::move(UUID);
	Parms.AnchorLocation = AnchorLocation;
	Parms.ActorClass = ActorClass;
	Parms.Owner = Owner;
	Parms.Instigator = Instigator;
	Parms.CollisionHandlingMethod = CollisionHandlingMethod;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorBPFunctionLibrary.SpawnActorWithAnchorQueryResults
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FOculusXRSpaceQueryResult& QueryResult                                            (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
// class UClass*                           ActorClass                                             (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class AActor*                           Owner                                                  (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class APawn*                            Instigator                                             (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ESpawnActorCollisionHandlingMethod      CollisionHandlingMethod                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class AActor*                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class AActor* UOculusXRAnchorBPFunctionLibrary::SpawnActorWithAnchorQueryResults(class UObject* WorldContextObject, const struct FOculusXRSpaceQueryResult& QueryResult, class UClass* ActorClass, class AActor* Owner, class APawn* Instigator, ESpawnActorCollisionHandlingMethod CollisionHandlingMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAnchorBPFunctionLibrary", "SpawnActorWithAnchorQueryResults");

	Params::OculusXRAnchorBPFunctionLibrary_SpawnActorWithAnchorQueryResults Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.QueryResult = std::move(QueryResult);
	Parms.ActorClass = ActorClass;
	Parms.Owner = Owner;
	Parms.Instigator = Instigator;
	Parms.CollisionHandlingMethod = CollisionHandlingMethod;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorBPFunctionLibrary.StringToAnchorUUID
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Value                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FOculusXRUUID                    ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FOculusXRUUID UOculusXRAnchorBPFunctionLibrary::StringToAnchorUUID(const class FString& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAnchorBPFunctionLibrary", "StringToAnchorUUID");

	Params::OculusXRAnchorBPFunctionLibrary_StringToAnchorUUID Parms{};

	Parms.Value = std::move(Value);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorBPFunctionLibrary.TryGetAnchorTransformByHandle
// (Final, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FOculusXRUInt64&           Handle                                                 (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FTransform*                      OutTransform                                           (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FOculusXRAnchorLocationFlags*    OutLocationFlags                                       (Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRAnchorBPFunctionLibrary::TryGetAnchorTransformByHandle(const struct FOculusXRUInt64& Handle, struct FTransform* OutTransform, struct FOculusXRAnchorLocationFlags* OutLocationFlags)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAnchorBPFunctionLibrary", "TryGetAnchorTransformByHandle");

	Params::OculusXRAnchorBPFunctionLibrary_TryGetAnchorTransformByHandle Parms{};

	Parms.Handle = std::move(Handle);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (OutTransform != nullptr)
		*OutTransform = std::move(Parms.OutTransform);

	if (OutLocationFlags != nullptr)
		*OutLocationFlags = std::move(Parms.OutLocationFlags);

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorComponent.SetHandle
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const struct FOculusXRUInt64&           Handle                                                 (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRAnchorComponent::SetHandle(const struct FOculusXRUInt64& Handle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRAnchorComponent", "SetHandle");

	Params::OculusXRAnchorComponent_SetHandle Parms{};

	Parms.Handle = std::move(Handle);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRAnchors.OculusXRAnchorComponent.GetHandle
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FOculusXRUInt64                  ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FOculusXRUInt64 UOculusXRAnchorComponent::GetHandle() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRAnchorComponent", "GetHandle");

	Params::OculusXRAnchorComponent_GetHandle Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorComponent.GetUUID
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FOculusXRUUID                    ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FOculusXRUUID UOculusXRAnchorComponent::GetUUID() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRAnchorComponent", "GetUUID");

	Params::OculusXRAnchorComponent_GetUUID Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorComponent.HasValidHandle
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRAnchorComponent::HasValidHandle() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRAnchorComponent", "HasValidHandle");

	Params::OculusXRAnchorComponent_HasValidHandle Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorComponent.IsSaved
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRAnchorComponent::IsSaved() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRAnchorComponent", "IsSaved");

	Params::OculusXRAnchorComponent_IsSaved Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorComponent.IsStoredAtLocation
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// EOculusXRSpaceStorageLocation           Location                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRAnchorComponent::IsStoredAtLocation(EOculusXRSpaceStorageLocation Location) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRAnchorComponent", "IsStoredAtLocation");

	Params::OculusXRAnchorComponent_IsStoredAtLocation Parms{};

	Parms.Location = Location;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRBaseAnchorComponent.GetType
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// EOculusXRSpaceComponentType             ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

EOculusXRSpaceComponentType UOculusXRBaseAnchorComponent::GetType() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRBaseAnchorComponent", "GetType");

	Params::OculusXRBaseAnchorComponent_GetType Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRBaseAnchorComponent.IsComponentEnabled
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRBaseAnchorComponent::IsComponentEnabled() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRBaseAnchorComponent", "IsComponentEnabled");

	Params::OculusXRBaseAnchorComponent_IsComponentEnabled Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRLocatableAnchorComponent.GetTransform
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FTransform*                      OutTransform                                           (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRLocatableAnchorComponent::GetTransform(struct FTransform* OutTransform) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRLocatableAnchorComponent", "GetTransform");

	Params::OculusXRLocatableAnchorComponent_GetTransform Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (OutTransform != nullptr)
		*OutTransform = std::move(Parms.OutTransform);

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRPlaneAnchorComponent.GetPositionAndSize
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FVector*                         OutPosition                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector*                         outSize                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRPlaneAnchorComponent::GetPositionAndSize(struct FVector* OutPosition, struct FVector* outSize) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPlaneAnchorComponent", "GetPositionAndSize");

	Params::OculusXRPlaneAnchorComponent_GetPositionAndSize Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (OutPosition != nullptr)
		*OutPosition = std::move(Parms.OutPosition);

	if (outSize != nullptr)
		*outSize = std::move(Parms.outSize);

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRVolumeAnchorComponent.GetPositionAndSize
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FVector*                         OutPosition                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector*                         outSize                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRVolumeAnchorComponent::GetPositionAndSize(struct FVector* OutPosition, struct FVector* outSize) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRVolumeAnchorComponent", "GetPositionAndSize");

	Params::OculusXRVolumeAnchorComponent_GetPositionAndSize Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (OutPosition != nullptr)
		*OutPosition = std::move(Parms.OutPosition);

	if (outSize != nullptr)
		*outSize = std::move(Parms.outSize);

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRSemanticClassificationAnchorComponent.GetSemanticClassifications
// (Final, Native, Public, HasOutParams, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// TArray<class FString>*                  outClassifications                                     (Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRSemanticClassificationAnchorComponent::GetSemanticClassifications(TArray<class FString>* outClassifications) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRSemanticClassificationAnchorComponent", "GetSemanticClassifications");

	Params::OculusXRSemanticClassificationAnchorComponent_GetSemanticClassifications Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (outClassifications != nullptr)
		*outClassifications = std::move(Parms.outClassifications);

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRRoomLayoutAnchorComponent.GetRoomLayout
// (Final, Native, Public, HasOutParams, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FOculusXRUUID*                   outFloorUUID                                           (Parm, OutParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FOculusXRUUID*                   outCeilingUUID                                         (Parm, OutParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<struct FOculusXRUUID>*           outWallsUUIDs                                          (Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRRoomLayoutAnchorComponent::GetRoomLayout(struct FOculusXRUUID* outFloorUUID, struct FOculusXRUUID* outCeilingUUID, TArray<struct FOculusXRUUID>* outWallsUUIDs) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRRoomLayoutAnchorComponent", "GetRoomLayout");

	Params::OculusXRRoomLayoutAnchorComponent_GetRoomLayout Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (outFloorUUID != nullptr)
		*outFloorUUID = std::move(Parms.outFloorUUID);

	if (outCeilingUUID != nullptr)
		*outCeilingUUID = std::move(Parms.outCeilingUUID);

	if (outWallsUUIDs != nullptr)
		*outWallsUUIDs = std::move(Parms.outWallsUUIDs);

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRSpaceContainerAnchorComponent.GetUUIDs
// (Final, Native, Public, HasOutParams, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// TArray<struct FOculusXRUUID>*           outUUIDs                                               (Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRSpaceContainerAnchorComponent::GetUUIDs(TArray<struct FOculusXRUUID>* outUUIDs) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRSpaceContainerAnchorComponent", "GetUUIDs");

	Params::OculusXRSpaceContainerAnchorComponent_GetUUIDs Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (outUUIDs != nullptr)
		*outUUIDs = std::move(Parms.outUUIDs);

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAsyncAction_CreateSpatialAnchor.OculusXRAsyncCreateSpatialAnchor
// (Final, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// class AActor*                           TargetActor_0                                          (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FTransform&                AnchorTransform                                        (ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOculusXRAsyncAction_CreateSpatialAnchor*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOculusXRAsyncAction_CreateSpatialAnchor* UOculusXRAsyncAction_CreateSpatialAnchor::OculusXRAsyncCreateSpatialAnchor(class AActor* TargetActor_0, const struct FTransform& AnchorTransform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAsyncAction_CreateSpatialAnchor", "OculusXRAsyncCreateSpatialAnchor");

	Params::OculusXRAsyncAction_CreateSpatialAnchor_OculusXRAsyncCreateSpatialAnchor Parms{};

	Parms.TargetActor_0 = TargetActor_0;
	Parms.AnchorTransform = std::move(AnchorTransform);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAsyncAction_EraseAnchor.OculusXRAsyncEraseAnchor
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class AActor*                           TargetActor_0                                          (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOculusXRAsyncAction_EraseAnchor* ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOculusXRAsyncAction_EraseAnchor* UOculusXRAsyncAction_EraseAnchor::OculusXRAsyncEraseAnchor(class AActor* TargetActor_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAsyncAction_EraseAnchor", "OculusXRAsyncEraseAnchor");

	Params::OculusXRAsyncAction_EraseAnchor_OculusXRAsyncEraseAnchor Parms{};

	Parms.TargetActor_0 = TargetActor_0;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAsyncAction_SaveAnchor.OculusXRAsyncSaveAnchor
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class AActor*                           TargetActor_0                                          (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EOculusXRSpaceStorageLocation           StorageLocation                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOculusXRAsyncAction_SaveAnchor*  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOculusXRAsyncAction_SaveAnchor* UOculusXRAsyncAction_SaveAnchor::OculusXRAsyncSaveAnchor(class AActor* TargetActor_0, EOculusXRSpaceStorageLocation StorageLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAsyncAction_SaveAnchor", "OculusXRAsyncSaveAnchor");

	Params::OculusXRAsyncAction_SaveAnchor_OculusXRAsyncSaveAnchor Parms{};

	Parms.TargetActor_0 = TargetActor_0;
	Parms.StorageLocation = StorageLocation;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAsyncAction_SaveAnchorList.OculusXRAsyncSaveAnchorList
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const TArray<class AActor*>&            TargetActors                                           (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// EOculusXRSpaceStorageLocation           StorageLocation                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOculusXRAsyncAction_SaveAnchorList*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOculusXRAsyncAction_SaveAnchorList* UOculusXRAsyncAction_SaveAnchorList::OculusXRAsyncSaveAnchorList(const TArray<class AActor*>& TargetActors, EOculusXRSpaceStorageLocation StorageLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAsyncAction_SaveAnchorList", "OculusXRAsyncSaveAnchorList");

	Params::OculusXRAsyncAction_SaveAnchorList_OculusXRAsyncSaveAnchorList Parms{};

	Parms.TargetActors = std::move(TargetActors);
	Parms.StorageLocation = StorageLocation;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAsyncAction_QueryAnchors.OculusXRAsyncQueryAnchors
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// EOculusXRSpaceStorageLocation           Location                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const TArray<struct FOculusXRUUID>&     UUIDs                                                  (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// class UOculusXRAsyncAction_QueryAnchors*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOculusXRAsyncAction_QueryAnchors* UOculusXRAsyncAction_QueryAnchors::OculusXRAsyncQueryAnchors(EOculusXRSpaceStorageLocation Location, const TArray<struct FOculusXRUUID>& UUIDs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAsyncAction_QueryAnchors", "OculusXRAsyncQueryAnchors");

	Params::OculusXRAsyncAction_QueryAnchors_OculusXRAsyncQueryAnchors Parms{};

	Parms.Location = Location;
	Parms.UUIDs = std::move(UUIDs);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAsyncAction_QueryAnchors.OculusXRAsyncQueryAnchorsAdvanced
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FOculusXRSpaceQueryInfo&   QueryInfo                                              (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
// class UOculusXRAsyncAction_QueryAnchors*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOculusXRAsyncAction_QueryAnchors* UOculusXRAsyncAction_QueryAnchors::OculusXRAsyncQueryAnchorsAdvanced(const struct FOculusXRSpaceQueryInfo& QueryInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAsyncAction_QueryAnchors", "OculusXRAsyncQueryAnchorsAdvanced");

	Params::OculusXRAsyncAction_QueryAnchors_OculusXRAsyncQueryAnchorsAdvanced Parms{};

	Parms.QueryInfo = std::move(QueryInfo);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAsyncAction_SetAnchorComponentStatus.OculusXRAsyncSetAnchorComponentStatus
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class AActor*                           TargetActor_0                                          (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EOculusXRSpaceComponentType             ComponentType                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bEnabled                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOculusXRAsyncAction_SetAnchorComponentStatus*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOculusXRAsyncAction_SetAnchorComponentStatus* UOculusXRAsyncAction_SetAnchorComponentStatus::OculusXRAsyncSetAnchorComponentStatus(class AActor* TargetActor_0, EOculusXRSpaceComponentType ComponentType, bool bEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAsyncAction_SetAnchorComponentStatus", "OculusXRAsyncSetAnchorComponentStatus");

	Params::OculusXRAsyncAction_SetAnchorComponentStatus_OculusXRAsyncSetAnchorComponentStatus Parms{};

	Parms.TargetActor_0 = TargetActor_0;
	Parms.ComponentType = ComponentType;
	Parms.bEnabled = bEnabled;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAsyncAction_SetComponentStatus.OculusXRAsyncSetComponentStatus
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UOculusXRBaseAnchorComponent*     Component_0                                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bEnabled                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOculusXRAsyncAction_SetComponentStatus*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOculusXRAsyncAction_SetComponentStatus* UOculusXRAsyncAction_SetComponentStatus::OculusXRAsyncSetComponentStatus(class UOculusXRBaseAnchorComponent* Component_0, bool bEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAsyncAction_SetComponentStatus", "OculusXRAsyncSetComponentStatus");

	Params::OculusXRAsyncAction_SetComponentStatus_OculusXRAsyncSetComponentStatus Parms{};

	Parms.Component_0 = Component_0;
	Parms.bEnabled = bEnabled;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAsyncAction_ShareAnchors.OculusXRAsyncShareAnchors
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const TArray<class AActor*>&            TargetActors                                           (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// const TArray<class FString>&            ToShareWithIds                                         (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// class UOculusXRAsyncAction_ShareAnchors*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOculusXRAsyncAction_ShareAnchors* UOculusXRAsyncAction_ShareAnchors::OculusXRAsyncShareAnchors(const TArray<class AActor*>& TargetActors, const TArray<class FString>& ToShareWithIds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAsyncAction_ShareAnchors", "OculusXRAsyncShareAnchors");

	Params::OculusXRAsyncAction_ShareAnchors_OculusXRAsyncShareAnchors Parms{};

	Parms.TargetActors = std::move(TargetActors);
	Parms.ToShareWithIds = std::move(ToShareWithIds);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAsyncAction_SaveAnchors.OculusXRAsyncSaveAnchors
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const TArray<class AActor*>&            TargetActors                                           (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// class UOculusXRAsyncAction_SaveAnchors* ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOculusXRAsyncAction_SaveAnchors* UOculusXRAsyncAction_SaveAnchors::OculusXRAsyncSaveAnchors(const TArray<class AActor*>& TargetActors)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAsyncAction_SaveAnchors", "OculusXRAsyncSaveAnchors");

	Params::OculusXRAsyncAction_SaveAnchors_OculusXRAsyncSaveAnchors Parms{};

	Parms.TargetActors = std::move(TargetActors);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAsyncAction_EraseAnchors.OculusXRAsyncEraseAnchors
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const TArray<class AActor*>&            TargetActors                                           (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// const TArray<struct FOculusXRUInt64>&   AnchorHandles                                          (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// const TArray<struct FOculusXRUUID>&     AnchorUUIDs                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// class UOculusXRAsyncAction_EraseAnchors*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOculusXRAsyncAction_EraseAnchors* UOculusXRAsyncAction_EraseAnchors::OculusXRAsyncEraseAnchors(const TArray<class AActor*>& TargetActors, const TArray<struct FOculusXRUInt64>& AnchorHandles, const TArray<struct FOculusXRUUID>& AnchorUUIDs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAsyncAction_EraseAnchors", "OculusXRAsyncEraseAnchors");

	Params::OculusXRAsyncAction_EraseAnchors_OculusXRAsyncEraseAnchors Parms{};

	Parms.TargetActors = std::move(TargetActors);
	Parms.AnchorHandles = std::move(AnchorHandles);
	Parms.AnchorUUIDs = std::move(AnchorUUIDs);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAsyncAction_DiscoverAnchors.OculusXRAsyncDiscoverAnchors
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FOculusXRSpaceDiscoveryInfo&DiscoveryInfo_0                                        (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
// class UOculusXRAsyncAction_DiscoverAnchors*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOculusXRAsyncAction_DiscoverAnchors* UOculusXRAsyncAction_DiscoverAnchors::OculusXRAsyncDiscoverAnchors(const struct FOculusXRSpaceDiscoveryInfo& DiscoveryInfo_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAsyncAction_DiscoverAnchors", "OculusXRAsyncDiscoverAnchors");

	Params::OculusXRAsyncAction_DiscoverAnchors_OculusXRAsyncDiscoverAnchors Parms{};

	Parms.DiscoveryInfo_0 = std::move(DiscoveryInfo_0);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAsyncAction_GetSharedAnchors.OculusXRAsyncGetSharedAnchors
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const TArray<struct FOculusXRUUID>&     AnchorUUIDs                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// class UOculusXRAsyncAction_GetSharedAnchors*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOculusXRAsyncAction_GetSharedAnchors* UOculusXRAsyncAction_GetSharedAnchors::OculusXRAsyncGetSharedAnchors(const TArray<struct FOculusXRUUID>& AnchorUUIDs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAsyncAction_GetSharedAnchors", "OculusXRAsyncGetSharedAnchors");

	Params::OculusXRAsyncAction_GetSharedAnchors_OculusXRAsyncGetSharedAnchors Parms{};

	Parms.AnchorUUIDs = std::move(AnchorUUIDs);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorLaunchCaptureFlow.LaunchCaptureFlowAsync
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class UObject*                    WorldContext                                           (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOculusXRAnchorLaunchCaptureFlow* ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOculusXRAnchorLaunchCaptureFlow* UOculusXRAnchorLaunchCaptureFlow::LaunchCaptureFlowAsync(const class UObject* WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OculusXRAnchorLaunchCaptureFlow", "LaunchCaptureFlowAsync");

	Params::OculusXRAnchorLaunchCaptureFlow_LaunchCaptureFlowAsync Parms{};

	Parms.WorldContext = WorldContext;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRAnchorLaunchCaptureFlow.OnCaptureFinish
// (Final, Native, Private)
// Parameters:
// const struct FOculusXRUInt64&           RequestID                                              (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bSuccess                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRAnchorLaunchCaptureFlow::OnCaptureFinish(const struct FOculusXRUInt64& RequestID, bool bSuccess)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRAnchorLaunchCaptureFlow", "OnCaptureFinish");

	Params::OculusXRAnchorLaunchCaptureFlow_OnCaptureFinish Parms{};

	Parms.RequestID = std::move(RequestID);
	Parms.bSuccess = bSuccess;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRAnchors.OculusXRRoomLayoutManagerComponent.GetRoomLayout
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FOculusXRUInt64&           Space                                                  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FOculusXRRoomLayout&             RoomLayoutOut                                          (Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
// int32                                   MaxWallsCapacity                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRRoomLayoutManagerComponent::GetRoomLayout(const struct FOculusXRUInt64& Space, struct FOculusXRRoomLayout& RoomLayoutOut, int32 MaxWallsCapacity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRRoomLayoutManagerComponent", "GetRoomLayout");

	Params::OculusXRRoomLayoutManagerComponent_GetRoomLayout Parms{};

	Parms.Space = std::move(Space);
	Parms.RoomLayoutOut = std::move(RoomLayoutOut);
	Parms.MaxWallsCapacity = MaxWallsCapacity;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	RoomLayoutOut = std::move(Parms.RoomLayoutOut);

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRRoomLayoutManagerComponent.LaunchCaptureFlow
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRRoomLayoutManagerComponent::LaunchCaptureFlow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRRoomLayoutManagerComponent", "LaunchCaptureFlow");

	Params::OculusXRRoomLayoutManagerComponent_LaunchCaptureFlow Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRAnchors.OculusXRRoomLayoutManagerComponent.OculusRoomLayoutSceneCaptureComplete_Handler
// (Final, Native, Private)
// Parameters:
// const struct FOculusXRUInt64&           RequestID                                              (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bSuccess                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRRoomLayoutManagerComponent::OculusRoomLayoutSceneCaptureComplete_Handler(const struct FOculusXRUInt64& RequestID, bool bSuccess)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRRoomLayoutManagerComponent", "OculusRoomLayoutSceneCaptureComplete_Handler");

	Params::OculusXRRoomLayoutManagerComponent_OculusRoomLayoutSceneCaptureComplete_Handler Parms{};

	Parms.RequestID = std::move(RequestID);
	Parms.bSuccess = bSuccess;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRAnchors.OculusXRRoomLayoutManagerComponent.LoadTriangleMesh
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const struct FOculusXRUInt64&           Space                                                  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UProceduralMeshComponent*         mesh                                                   (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    CreateCollision                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRRoomLayoutManagerComponent::LoadTriangleMesh(const struct FOculusXRUInt64& Space, class UProceduralMeshComponent* mesh, bool CreateCollision) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRRoomLayoutManagerComponent", "LoadTriangleMesh");

	Params::OculusXRRoomLayoutManagerComponent_LoadTriangleMesh Parms{};

	Parms.Space = std::move(Space);
	Parms.mesh = mesh;
	Parms.CreateCollision = CreateCollision;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
