#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OculusXRPassthrough

#include "Basic.hpp"

#include "OculusXRPassthrough_classes.hpp"
#include "OculusXRPassthrough_parameters.hpp"


SDK_NAMESPACE_START

// Function OculusXRPassthrough.OculusXRPassthroughColorLut.SetLutFromArray
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const TArray<struct FColor>&            InColorArray                                           (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// bool                                    InIgnoreAlphaChannel                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughColorLut::SetLutFromArray(const TArray<struct FColor>& InColorArray, bool InIgnoreAlphaChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughColorLut", "SetLutFromArray");

	Params::OculusXRPassthroughColorLut_SetLutFromArray Parms{};

	Parms.InColorArray = std::move(InColorArray);
	Parms.InIgnoreAlphaChannel = InIgnoreAlphaChannel;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.ClearColorMap
// (Final, Native, Public, BlueprintCallable)

void UOculusXRPassthroughLayerBase::ClearColorMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "ClearColorMap");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.EnableColorMap
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInEnableColorMap                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerBase::EnableColorMap(bool bInEnableColorMap)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "EnableColorMap");

	Params::OculusXRPassthroughLayerBase_EnableColorMap Parms{};

	Parms.bInEnableColorMap = bInEnableColorMap;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.EnableColorMapCurve
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInEnableColorMapCurve                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerBase::EnableColorMapCurve(bool bInEnableColorMapCurve)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "EnableColorMapCurve");

	Params::OculusXRPassthroughLayerBase_EnableColorMapCurve Parms{};

	Parms.bInEnableColorMapCurve = bInEnableColorMapCurve;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.EnableEdgeColor
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInEnableEdgeColor                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerBase::EnableEdgeColor(bool bInEnableEdgeColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "EnableEdgeColor");

	Params::OculusXRPassthroughLayerBase_EnableEdgeColor Parms{};

	Parms.bInEnableEdgeColor = bInEnableEdgeColor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.RemoveColorLut
// (Final, Native, Public, BlueprintCallable)

void UOculusXRPassthroughLayerBase::RemoveColorLut()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "RemoveColorLut");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.SetBrightnessContrastSaturation
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InContrast                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   InBrightness                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   InSaturation                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerBase::SetBrightnessContrastSaturation(float InContrast, float InBrightness, float InSaturation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "SetBrightnessContrastSaturation");

	Params::OculusXRPassthroughLayerBase_SetBrightnessContrastSaturation Parms{};

	Parms.InContrast = InContrast;
	Parms.InBrightness = InBrightness;
	Parms.InSaturation = InSaturation;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.SetColorArray
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const TArray<struct FLinearColor>&      InColorArray                                           (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerBase::SetColorArray(const TArray<struct FLinearColor>& InColorArray)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "SetColorArray");

	Params::OculusXRPassthroughLayerBase_SetColorArray Parms{};

	Parms.InColorArray = std::move(InColorArray);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.SetColorLUTSource
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UOculusXRPassthroughColorLut*     InColorLUTSource                                       (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerBase::SetColorLUTSource(class UOculusXRPassthroughColorLut* InColorLUTSource)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "SetColorLUTSource");

	Params::OculusXRPassthroughLayerBase_SetColorLUTSource Parms{};

	Parms.InColorLUTSource = InColorLUTSource;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.SetColorLUTTarget
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UOculusXRPassthroughColorLut*     InColorLUTTarget                                       (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerBase::SetColorLUTTarget(class UOculusXRPassthroughColorLut* InColorLUTTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "SetColorLUTTarget");

	Params::OculusXRPassthroughLayerBase_SetColorLUTTarget Parms{};

	Parms.InColorLUTTarget = InColorLUTTarget;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.SetColorLUTWeight
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InWeight                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerBase::SetColorLUTWeight(float InWeight)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "SetColorLUTWeight");

	Params::OculusXRPassthroughLayerBase_SetColorLUTWeight Parms{};

	Parms.InWeight = InWeight;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.SetColorMapControls
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InContrast                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   InBrightness                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   InPosterize                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerBase::SetColorMapControls(float InContrast, float InBrightness, float InPosterize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "SetColorMapControls");

	Params::OculusXRPassthroughLayerBase_SetColorMapControls Parms{};

	Parms.InContrast = InContrast;
	Parms.InBrightness = InBrightness;
	Parms.InPosterize = InPosterize;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.SetColorMapCurve
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UCurveLinearColor*                InColorMapCurve                                        (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerBase::SetColorMapCurve(class UCurveLinearColor* InColorMapCurve)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "SetColorMapCurve");

	Params::OculusXRPassthroughLayerBase_SetColorMapCurve Parms{};

	Parms.InColorMapCurve = InColorMapCurve;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.SetColorMapType
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// EOculusXRColorMapType                   InColorMapType                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerBase::SetColorMapType(EOculusXRColorMapType InColorMapType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "SetColorMapType");

	Params::OculusXRPassthroughLayerBase_SetColorMapType Parms{};

	Parms.InColorMapType = InColorMapType;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.SetColorScaleAndOffset
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FLinearColor&              InColorScale                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FLinearColor&              InColorOffset                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerBase::SetColorScaleAndOffset(const struct FLinearColor& InColorScale, const struct FLinearColor& InColorOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "SetColorScaleAndOffset");

	Params::OculusXRPassthroughLayerBase_SetColorScaleAndOffset Parms{};

	Parms.InColorScale = std::move(InColorScale);
	Parms.InColorOffset = std::move(InColorOffset);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.SetEdgeRenderingColor
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FLinearColor&              InEdgeColor                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerBase::SetEdgeRenderingColor(const struct FLinearColor& InEdgeColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "SetEdgeRenderingColor");

	Params::OculusXRPassthroughLayerBase_SetEdgeRenderingColor Parms{};

	Parms.InEdgeColor = std::move(InEdgeColor);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.SetLayerPlacement
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// EOculusXRPassthroughLayerOrder          InLayerOrder                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerBase::SetLayerPlacement(EOculusXRPassthroughLayerOrder InLayerOrder)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "SetLayerPlacement");

	Params::OculusXRPassthroughLayerBase_SetLayerPlacement Parms{};

	Parms.InLayerOrder = InLayerOrder;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerBase.SetTextureOpacity
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InOpacity                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerBase::SetTextureOpacity(float InOpacity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerBase", "SetTextureOpacity");

	Params::OculusXRPassthroughLayerBase_SetTextureOpacity Parms{};

	Parms.InOpacity = InOpacity;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerComponent.AddProceduralSurfaceGeometry
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UProceduralMeshComponent*         ProceduralMeshComponent                                (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    updateTransform                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerComponent::AddProceduralSurfaceGeometry(class UProceduralMeshComponent* ProceduralMeshComponent, bool updateTransform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerComponent", "AddProceduralSurfaceGeometry");

	Params::OculusXRPassthroughLayerComponent_AddProceduralSurfaceGeometry Parms{};

	Parms.ProceduralMeshComponent = ProceduralMeshComponent;
	Parms.updateTransform = updateTransform;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerComponent.AddStaticSurfaceGeometry
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UStaticMeshComponent*             StaticMeshComponent                                    (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    updateTransform                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerComponent::AddStaticSurfaceGeometry(class UStaticMeshComponent* StaticMeshComponent, bool updateTransform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerComponent", "AddStaticSurfaceGeometry");

	Params::OculusXRPassthroughLayerComponent_AddStaticSurfaceGeometry Parms{};

	Parms.StaticMeshComponent = StaticMeshComponent;
	Parms.updateTransform = updateTransform;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerComponent.AddSurfaceGeometry
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class AStaticMeshActor*                 StaticMeshActor                                        (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    updateTransform                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerComponent::AddSurfaceGeometry(class AStaticMeshActor* StaticMeshActor, bool updateTransform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerComponent", "AddSurfaceGeometry");

	Params::OculusXRPassthroughLayerComponent_AddSurfaceGeometry Parms{};

	Parms.StaticMeshActor = StaticMeshActor;
	Parms.updateTransform = updateTransform;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerComponent.MarkPassthroughStyleForUpdate
// (Final, Native, Public, BlueprintCallable)

void UOculusXRPassthroughLayerComponent::MarkPassthroughStyleForUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerComponent", "MarkPassthroughStyleForUpdate");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerComponent.RemoveProceduralSurfaceGeometry
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UProceduralMeshComponent*         ProceduralMeshComponent                                (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerComponent::RemoveProceduralSurfaceGeometry(class UProceduralMeshComponent* ProceduralMeshComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerComponent", "RemoveProceduralSurfaceGeometry");

	Params::OculusXRPassthroughLayerComponent_RemoveProceduralSurfaceGeometry Parms{};

	Parms.ProceduralMeshComponent = ProceduralMeshComponent;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerComponent.RemoveStaticSurfaceGeometry
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UStaticMeshComponent*             StaticMeshComponent                                    (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerComponent::RemoveStaticSurfaceGeometry(class UStaticMeshComponent* StaticMeshComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerComponent", "RemoveStaticSurfaceGeometry");

	Params::OculusXRPassthroughLayerComponent_RemoveStaticSurfaceGeometry Parms{};

	Parms.StaticMeshComponent = StaticMeshComponent;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerComponent.RemoveSurfaceGeometry
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class AStaticMeshActor*                 StaticMeshActor                                        (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOculusXRPassthroughLayerComponent::RemoveSurfaceGeometry(class AStaticMeshActor* StaticMeshActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerComponent", "RemoveSurfaceGeometry");

	Params::OculusXRPassthroughLayerComponent_RemoveSurfaceGeometry Parms{};

	Parms.StaticMeshActor = StaticMeshActor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerComponent.IsSurfaceGeometry
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class AStaticMeshActor*                 StaticMeshActor                                        (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRPassthroughLayerComponent::IsSurfaceGeometry(class AStaticMeshActor* StaticMeshActor) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerComponent", "IsSurfaceGeometry");

	Params::OculusXRPassthroughLayerComponent_IsSurfaceGeometry Parms{};

	Parms.StaticMeshActor = StaticMeshActor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OculusXRPassthrough.OculusXRPassthroughLayerComponent.IsSurfaceGeometryComponent
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const class UMeshComponent*             MeshComponent                                          (ConstParm, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOculusXRPassthroughLayerComponent::IsSurfaceGeometryComponent(const class UMeshComponent* MeshComponent) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OculusXRPassthroughLayerComponent", "IsSurfaceGeometryComponent");

	Params::OculusXRPassthroughLayerComponent_IsSurfaceGeometryComponent Parms{};

	Parms.MeshComponent = MeshComponent;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
