#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OculusXRHMD

#include "Basic.hpp"

#include "HeadMountedDisplay_structs.hpp"
#include "OculusXRHMD_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "InputCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function OculusXRHMD.OculusXRFunctionLibrary.AddLoadingSplashScreen
// 0x0068 (0x0068 - 0x0000)
struct OculusXRFunctionLibrary_AddLoadingSplashScreen final
{
public:
	class UTexture2D*                             Texture;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                TranslationInMeters;                               // 0x0008(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               Rotation;                                          // 0x0020(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector2D                              SizeInMeters;                                      // 0x0038(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               DeltaRotation;                                     // 0x0048(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bClearBeforeAdd;                                   // 0x0060(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_AddLoadingSplashScreen;

// Function OculusXRHMD.OculusXRFunctionLibrary.EnableOrientationTracking
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_EnableOrientationTracking final
{
public:
	bool                                          bOrientationTracking;                              // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_EnableOrientationTracking;

// Function OculusXRHMD.OculusXRFunctionLibrary.EnablePositionTracking
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_EnablePositionTracking final
{
public:
	bool                                          bPositionTracking;                                 // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_EnablePositionTracking;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetAvailableDisplayFrequencies
// 0x0010 (0x0010 - 0x0000)
struct OculusXRFunctionLibrary_GetAvailableDisplayFrequencies final
{
public:
	TArray<float>                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetAvailableDisplayFrequencies;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetBaseRotationAndBaseOffsetInMeters
// 0x0030 (0x0030 - 0x0000)
struct OculusXRFunctionLibrary_GetBaseRotationAndBaseOffsetInMeters final
{
public:
	struct FRotator                               OutRotation;                                       // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector                                OutBaseOffsetInMeters;                             // 0x0018(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetBaseRotationAndBaseOffsetInMeters;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetBaseRotationAndPositionOffset
// 0x0030 (0x0030 - 0x0000)
struct OculusXRFunctionLibrary_GetBaseRotationAndPositionOffset final
{
public:
	struct FRotator                               OutRot;                                            // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector                                OutPosOffset;                                      // 0x0018(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetBaseRotationAndPositionOffset;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetControllerType
// 0x0002 (0x0002 - 0x0000)
struct OculusXRFunctionLibrary_GetControllerType final
{
public:
	EControllerHand                               deviceHand;                                        // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOculusXRControllerType                       ReturnValue;                                       // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetControllerType;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetCurrentDisplayFrequency
// 0x0004 (0x0004 - 0x0000)
struct OculusXRFunctionLibrary_GetCurrentDisplayFrequency final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetCurrentDisplayFrequency;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetDeviceName
// 0x0010 (0x0010 - 0x0000)
struct OculusXRFunctionLibrary_GetDeviceName final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetDeviceName;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetDeviceType
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_GetDeviceType final
{
public:
	EOculusXRDeviceType                           ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetDeviceType;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetEyeTrackedFoveatedRenderingSupported
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_GetEyeTrackedFoveatedRenderingSupported final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetEyeTrackedFoveatedRenderingSupported;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetFoveatedRenderingLevel
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_GetFoveatedRenderingLevel final
{
public:
	EOculusXRFoveatedRenderingLevel               ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetFoveatedRenderingLevel;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetFoveatedRenderingMethod
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_GetFoveatedRenderingMethod final
{
public:
	EOculusXRFoveatedRenderingMethod              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetFoveatedRenderingMethod;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetGPUFrameTime
// 0x0004 (0x0004 - 0x0000)
struct OculusXRFunctionLibrary_GetGPUFrameTime final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetGPUFrameTime;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetGPUUtilization
// 0x0008 (0x0008 - 0x0000)
struct OculusXRFunctionLibrary_GetGPUUtilization final
{
public:
	bool                                          IsGPUAvailable;                                    // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         GPUUtilization;                                    // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetGPUUtilization;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetGuardianDimensions
// 0x0020 (0x0020 - 0x0000)
struct OculusXRFunctionLibrary_GetGuardianDimensions final
{
public:
	EOculusXRBoundaryType                         BoundaryType;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                ReturnValue;                                       // 0x0008(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetGuardianDimensions;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetGuardianPoints
// 0x0018 (0x0018 - 0x0000)
struct OculusXRFunctionLibrary_GetGuardianPoints final
{
public:
	EOculusXRBoundaryType                         BoundaryType;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          UsePawnSpace;                                      // 0x0001(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FVector>                        ReturnValue;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetGuardianPoints;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetHmdColorDesc
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_GetHmdColorDesc final
{
public:
	EOculusXRColorSpace                           ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetHmdColorDesc;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetNodeGuardianIntersection
// 0x0040 (0x0040 - 0x0000)
struct OculusXRFunctionLibrary_GetNodeGuardianIntersection final
{
public:
	EOculusXRTrackedDeviceType                    DeviceType;                                        // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOculusXRBoundaryType                         BoundaryType;                                      // 0x0001(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOculusXRGuardianTestResult            ReturnValue;                                       // 0x0008(0x0038)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetNodeGuardianIntersection;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetPerformanceMetrics
// 0x0038 (0x0038 - 0x0000)
struct OculusXRFunctionLibrary_GetPerformanceMetrics final
{
public:
	struct FOculusXRPerformanceMetrics            PerformanceMetrics;                                // 0x0000(0x0038)(Parm, OutParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetPerformanceMetrics;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetPlayAreaTransform
// 0x0060 (0x0060 - 0x0000)
struct OculusXRFunctionLibrary_GetPlayAreaTransform final
{
public:
	struct FTransform                             ReturnValue;                                       // 0x0000(0x0060)(Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetPlayAreaTransform;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetPointGuardianIntersection
// 0x0058 (0x0058 - 0x0000)
struct OculusXRFunctionLibrary_GetPointGuardianIntersection final
{
public:
	struct FVector                                Point;                                             // 0x0000(0x0018)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOculusXRBoundaryType                         BoundaryType;                                      // 0x0018(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOculusXRGuardianTestResult            ReturnValue;                                       // 0x0020(0x0038)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetPointGuardianIntersection;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetPose
// 0x0068 (0x0068 - 0x0000)
struct OculusXRFunctionLibrary_GetPose final
{
public:
	struct FRotator                               DeviceRotation;                                    // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector                                DevicePosition;                                    // 0x0018(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                NeckPosition;                                      // 0x0030(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseOrienationForPlayerCamera;                     // 0x0048(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUsePositionForPlayerCamera;                       // 0x0049(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4A[0x6];                                       // 0x004A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                PositionScale;                                     // 0x0050(0x0018)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetPose;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetRawSensorData
// 0x0068 (0x0068 - 0x0000)
struct OculusXRFunctionLibrary_GetRawSensorData final
{
public:
	struct FVector                                AngularAcceleration;                               // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                LinearAcceleration;                                // 0x0018(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                AngularVelocity;                                   // 0x0030(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                LinearVelocity;                                    // 0x0048(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TimeInSeconds;                                     // 0x0060(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOculusXRTrackedDeviceType                    DeviceType;                                        // 0x0064(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_65[0x3];                                       // 0x0065(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetRawSensorData;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetSuggestedCpuAndGpuPerformanceLevels
// 0x0002 (0x0002 - 0x0000)
struct OculusXRFunctionLibrary_GetSuggestedCpuAndGpuPerformanceLevels final
{
public:
	EOculusXRProcessorPerformanceLevel            CpuPerfLevel;                                      // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOculusXRProcessorPerformanceLevel            GpuPerfLevel;                                      // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetSuggestedCpuAndGpuPerformanceLevels;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetSystemHmd3DofModeEnabled
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_GetSystemHmd3DofModeEnabled final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetSystemHmd3DofModeEnabled;

// Function OculusXRHMD.OculusXRFunctionLibrary.GetUserProfile
// 0x0058 (0x0058 - 0x0000)
struct OculusXRFunctionLibrary_GetUserProfile final
{
public:
	struct FOculusXRHmdUserProfile                Profile;                                           // 0x0000(0x0050)(Parm, OutParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0050(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_GetUserProfile;

// Function OculusXRHMD.OculusXRFunctionLibrary.HasInputFocus
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_HasInputFocus final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_HasInputFocus;

// Function OculusXRHMD.OculusXRFunctionLibrary.HasSystemOverlayPresent
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_HasSystemOverlayPresent final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_HasSystemOverlayPresent;

// Function OculusXRHMD.OculusXRFunctionLibrary.IsColorPassthroughSupported
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_IsColorPassthroughSupported final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_IsColorPassthroughSupported;

// Function OculusXRHMD.OculusXRFunctionLibrary.IsDeviceTracked
// 0x0002 (0x0002 - 0x0000)
struct OculusXRFunctionLibrary_IsDeviceTracked final
{
public:
	EOculusXRTrackedDeviceType                    DeviceType;                                        // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_IsDeviceTracked;

// Function OculusXRHMD.OculusXRFunctionLibrary.IsEnvironmentDepthStarted
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_IsEnvironmentDepthStarted final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_IsEnvironmentDepthStarted;

// Function OculusXRHMD.OculusXRFunctionLibrary.IsGuardianConfigured
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_IsGuardianConfigured final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_IsGuardianConfigured;

// Function OculusXRHMD.OculusXRFunctionLibrary.IsGuardianDisplayed
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_IsGuardianDisplayed final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_IsGuardianDisplayed;

// Function OculusXRHMD.OculusXRFunctionLibrary.IsPassthroughRecommended
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_IsPassthroughRecommended final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_IsPassthroughRecommended;

// Function OculusXRHMD.OculusXRFunctionLibrary.IsPassthroughSupported
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_IsPassthroughSupported final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_IsPassthroughSupported;

// Function OculusXRHMD.OculusXRFunctionLibrary.SetBaseRotationAndBaseOffsetInMeters
// 0x0038 (0x0038 - 0x0000)
struct OculusXRFunctionLibrary_SetBaseRotationAndBaseOffsetInMeters final
{
public:
	struct FRotator                               Rotation;                                          // 0x0000(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector                                BaseOffsetInMeters;                                // 0x0018(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOrientPositionSelector                       Options;                                           // 0x0030(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_SetBaseRotationAndBaseOffsetInMeters;

// Function OculusXRHMD.OculusXRFunctionLibrary.SetBaseRotationAndPositionOffset
// 0x0038 (0x0038 - 0x0000)
struct OculusXRFunctionLibrary_SetBaseRotationAndPositionOffset final
{
public:
	struct FRotator                               BaseRot;                                           // 0x0000(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector                                PosOffset;                                         // 0x0018(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOrientPositionSelector                       Options;                                           // 0x0030(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_SetBaseRotationAndPositionOffset;

// Function OculusXRHMD.OculusXRFunctionLibrary.SetClientColorDesc
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_SetClientColorDesc final
{
public:
	EOculusXRColorSpace                           ColorSpace;                                        // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_SetClientColorDesc;

// Function OculusXRHMD.OculusXRFunctionLibrary.SetColorScaleAndOffset
// 0x0024 (0x0024 - 0x0000)
struct OculusXRFunctionLibrary_SetColorScaleAndOffset final
{
public:
	struct FLinearColor                           ColorScale;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           ColorOffset;                                       // 0x0010(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bApplyToAllLayers;                                 // 0x0020(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_SetColorScaleAndOffset;

// Function OculusXRHMD.OculusXRFunctionLibrary.SetCPUAndGPULevels
// 0x0008 (0x0008 - 0x0000)
struct OculusXRFunctionLibrary_SetCPUAndGPULevels final
{
public:
	int32                                         CPULevel;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         GPULevel;                                          // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_SetCPUAndGPULevels;

// Function OculusXRHMD.OculusXRFunctionLibrary.SetDisplayFrequency
// 0x0004 (0x0004 - 0x0000)
struct OculusXRFunctionLibrary_SetDisplayFrequency final
{
public:
	float                                         RequestedFrequency;                                // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_SetDisplayFrequency;

// Function OculusXRHMD.OculusXRFunctionLibrary.SetEnvironmentDepthHandRemoval
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_SetEnvironmentDepthHandRemoval final
{
public:
	bool                                          RemoveHands;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_SetEnvironmentDepthHandRemoval;

// Function OculusXRHMD.OculusXRFunctionLibrary.SetEyeBufferSharpenType
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_SetEyeBufferSharpenType final
{
public:
	EOculusXREyeBufferSharpenType                 EyeBufferSharpenType;                              // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_SetEyeBufferSharpenType;

// Function OculusXRHMD.OculusXRFunctionLibrary.SetFoveatedRenderingLevel
// 0x0002 (0x0002 - 0x0000)
struct OculusXRFunctionLibrary_SetFoveatedRenderingLevel final
{
public:
	EOculusXRFoveatedRenderingLevel               Level;                                             // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          isDynamic;                                         // 0x0001(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_SetFoveatedRenderingLevel;

// Function OculusXRHMD.OculusXRFunctionLibrary.SetFoveatedRenderingMethod
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_SetFoveatedRenderingMethod final
{
public:
	EOculusXRFoveatedRenderingMethod              Method;                                            // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_SetFoveatedRenderingMethod;

// Function OculusXRHMD.OculusXRFunctionLibrary.SetGuardianVisibility
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_SetGuardianVisibility final
{
public:
	bool                                          GuardianVisible;                                   // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_SetGuardianVisibility;

// Function OculusXRHMD.OculusXRFunctionLibrary.SetLocalDimmingOn
// 0x0001 (0x0001 - 0x0000)
struct OculusXRFunctionLibrary_SetLocalDimmingOn final
{
public:
	bool                                          LocalDimmingOn;                                    // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_SetLocalDimmingOn;

// Function OculusXRHMD.OculusXRFunctionLibrary.SetPositionScale3D
// 0x0018 (0x0018 - 0x0000)
struct OculusXRFunctionLibrary_SetPositionScale3D final
{
public:
	struct FVector                                PosScale3D;                                        // 0x0000(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_SetPositionScale3D;

// Function OculusXRHMD.OculusXRFunctionLibrary.SetSuggestedCpuAndGpuPerformanceLevels
// 0x0002 (0x0002 - 0x0000)
struct OculusXRFunctionLibrary_SetSuggestedCpuAndGpuPerformanceLevels final
{
public:
	EOculusXRProcessorPerformanceLevel            CpuPerfLevel;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOculusXRProcessorPerformanceLevel            GpuPerfLevel;                                      // 0x0001(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_SetSuggestedCpuAndGpuPerformanceLevels;

// Function OculusXRHMD.OculusXRFunctionLibrary.SetXROcclusionsMode
// 0x0010 (0x0010 - 0x0000)
struct OculusXRFunctionLibrary_SetXROcclusionsMode final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOculusXROcclusionsMode                       Mode;                                              // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_OculusXRFunctionLibrary_SetXROcclusionsMode;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
