#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OVRPlatform

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "OVRPlatform_structs.hpp"
#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// Class OVRPlatform.OvrFunctionsBlueprintLibrary
// 0x0000 (0x0028 - 0x0028)
class UOvrFunctionsBlueprintLibrary final : public UBlueprintFunctionLibrary
{
public:
	static struct FOvrLaunchDetails ApplicationLifecycle_GetLaunchDetails();
	static void ApplicationLifecycle_LogDeeplinkResult(const class FString& TrackingID, EOvrLaunchResult Result);
	static struct FOvrId Platform_GetLoggedInUserID();
	static class FString Platform_GetLoggedInUserLocale();
	static bool Platform_IsInitialized();
	static void Platform_SetDeveloperAccessToken(const class FString& AccessToken);
	static void Voip_Accept(const struct FOvrId& UserId);
	static EOvrVoipDtxState Voip_GetIsConnectionUsingDtx(const struct FOvrId& PeerID);
	static EOvrVoipBitrate Voip_GetLocalBitrate(const struct FOvrId& PeerID);
	static int64 Voip_GetOutputBufferMaxSize();
	static int64 Voip_GetPCMSize(const struct FOvrId& SenderId);
	static EOvrVoipBitrate Voip_GetRemoteBitrate(const struct FOvrId& PeerID);
	static int32 Voip_GetSyncTimestamp(const struct FOvrId& UserId);
	static int64 Voip_GetSyncTimestampDifference(int32 LHS, int32 RHS);
	static EOvrVoipMuteState Voip_GetSystemVoipMicrophoneMuted();
	static EOvrSystemVoipStatus Voip_GetSystemVoipStatus();
	static void Voip_SetMicrophoneMuted(EOvrVoipMuteState State);
	static void Voip_SetNewConnectionOptions(const struct FOvrVoipOptions& VoipOptions);
	static void Voip_SetOutputSampleRate(EOvrVoipSampleRate Rate);
	static void Voip_Start(const struct FOvrId& UserId);
	static void Voip_Stop(const struct FOvrId& UserId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrFunctionsBlueprintLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrFunctionsBlueprintLibrary")
	}
	static class UOvrFunctionsBlueprintLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrFunctionsBlueprintLibrary>();
	}
};
DUMPER7_ASSERTS_UOvrFunctionsBlueprintLibrary;

// Class OVRPlatform.OvrAchievementDefinitionPagesMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrAchievementDefinitionPagesMethods final : public UObject
{
public:
	static struct FOvrAchievementDefinition AchievementDefinitionPages_GetElement(const struct FOvrAchievementDefinitionPages& Model, int64 Index_0);
	static class FString AchievementDefinitionPages_GetNextUrl(const struct FOvrAchievementDefinitionPages& Model);
	static int64 AchievementDefinitionPages_GetSize(const struct FOvrAchievementDefinitionPages& Model);
	static bool AchievementDefinitionPages_HasNextPage(const struct FOvrAchievementDefinitionPages& Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrAchievementDefinitionPagesMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrAchievementDefinitionPagesMethods")
	}
	static class UOvrAchievementDefinitionPagesMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrAchievementDefinitionPagesMethods>();
	}
};
DUMPER7_ASSERTS_UOvrAchievementDefinitionPagesMethods;

// Class OVRPlatform.OvrAchievementProgressPagesMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrAchievementProgressPagesMethods final : public UObject
{
public:
	static struct FOvrAchievementProgress AchievementProgressPages_GetElement(const struct FOvrAchievementProgressPages& Model, int64 Index_0);
	static class FString AchievementProgressPages_GetNextUrl(const struct FOvrAchievementProgressPages& Model);
	static int64 AchievementProgressPages_GetSize(const struct FOvrAchievementProgressPages& Model);
	static bool AchievementProgressPages_HasNextPage(const struct FOvrAchievementProgressPages& Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrAchievementProgressPagesMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrAchievementProgressPagesMethods")
	}
	static class UOvrAchievementProgressPagesMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrAchievementProgressPagesMethods>();
	}
};
DUMPER7_ASSERTS_UOvrAchievementProgressPagesMethods;

// Class OVRPlatform.OvrBlockedUserPagesMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrBlockedUserPagesMethods final : public UObject
{
public:
	static struct FOvrBlockedUser BlockedUserPages_GetElement(const struct FOvrBlockedUserPages& Model, int64 Index_0);
	static class FString BlockedUserPages_GetNextUrl(const struct FOvrBlockedUserPages& Model);
	static int64 BlockedUserPages_GetSize(const struct FOvrBlockedUserPages& Model);
	static bool BlockedUserPages_HasNextPage(const struct FOvrBlockedUserPages& Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrBlockedUserPagesMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrBlockedUserPagesMethods")
	}
	static class UOvrBlockedUserPagesMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrBlockedUserPagesMethods>();
	}
};
DUMPER7_ASSERTS_UOvrBlockedUserPagesMethods;

// Class OVRPlatform.OvrCowatchViewerPagesMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrCowatchViewerPagesMethods final : public UObject
{
public:
	static struct FOvrCowatchViewer CowatchViewerPages_GetElement(const struct FOvrCowatchViewerPages& Model, int64 Index_0);
	static class FString CowatchViewerPages_GetNextUrl(const struct FOvrCowatchViewerPages& Model);
	static int64 CowatchViewerPages_GetSize(const struct FOvrCowatchViewerPages& Model);
	static bool CowatchViewerPages_HasNextPage(const struct FOvrCowatchViewerPages& Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrCowatchViewerPagesMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrCowatchViewerPagesMethods")
	}
	static class UOvrCowatchViewerPagesMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrCowatchViewerPagesMethods>();
	}
};
DUMPER7_ASSERTS_UOvrCowatchViewerPagesMethods;

// Class OVRPlatform.OvrDestinationPagesMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrDestinationPagesMethods final : public UObject
{
public:
	static struct FOvrDestination DestinationPages_GetElement(const struct FOvrDestinationPages& Model, int64 Index_0);
	static class FString DestinationPages_GetNextUrl(const struct FOvrDestinationPages& Model);
	static int64 DestinationPages_GetSize(const struct FOvrDestinationPages& Model);
	static bool DestinationPages_HasNextPage(const struct FOvrDestinationPages& Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrDestinationPagesMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrDestinationPagesMethods")
	}
	static class UOvrDestinationPagesMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrDestinationPagesMethods>();
	}
};
DUMPER7_ASSERTS_UOvrDestinationPagesMethods;

// Class OVRPlatform.OvrLeaderboardPagesMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrLeaderboardPagesMethods final : public UObject
{
public:
	static struct FOvrLeaderboard LeaderboardPages_GetElement(const struct FOvrLeaderboardPages& Model, int64 Index_0);
	static class FString LeaderboardPages_GetNextUrl(const struct FOvrLeaderboardPages& Model);
	static int64 LeaderboardPages_GetSize(const struct FOvrLeaderboardPages& Model);
	static bool LeaderboardPages_HasNextPage(const struct FOvrLeaderboardPages& Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrLeaderboardPagesMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrLeaderboardPagesMethods")
	}
	static class UOvrLeaderboardPagesMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrLeaderboardPagesMethods>();
	}
};
DUMPER7_ASSERTS_UOvrLeaderboardPagesMethods;

// Class OVRPlatform.OvrMicrophoneMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrMicrophoneMethods final : public UObject
{
public:
	static void Microphone_SetAcceptableRecordingDelayHint(struct FOvrMicrophone* Model, int64 DelayMs);
	static void Microphone_Start(struct FOvrMicrophone* Model);
	static void Microphone_Stop(struct FOvrMicrophone* Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrMicrophoneMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrMicrophoneMethods")
	}
	static class UOvrMicrophoneMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrMicrophoneMethods>();
	}
};
DUMPER7_ASSERTS_UOvrMicrophoneMethods;

// Class OVRPlatform.OvrPacketMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrPacketMethods final : public UObject
{
public:
	static void Packet_Free(struct FOvrPacket* Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrPacketMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrPacketMethods")
	}
	static class UOvrPacketMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrPacketMethods>();
	}
};
DUMPER7_ASSERTS_UOvrPacketMethods;

// Class OVRPlatform.OvrProductPagesMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrProductPagesMethods final : public UObject
{
public:
	static struct FOvrProduct ProductPages_GetElement(const struct FOvrProductPages& Model, int64 Index_0);
	static class FString ProductPages_GetNextUrl(const struct FOvrProductPages& Model);
	static int64 ProductPages_GetSize(const struct FOvrProductPages& Model);
	static bool ProductPages_HasNextPage(const struct FOvrProductPages& Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrProductPagesMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrProductPagesMethods")
	}
	static class UOvrProductPagesMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrProductPagesMethods>();
	}
};
DUMPER7_ASSERTS_UOvrProductPagesMethods;

// Class OVRPlatform.OvrPurchasePagesMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrPurchasePagesMethods final : public UObject
{
public:
	static struct FOvrPurchase PurchasePages_GetElement(const struct FOvrPurchasePages& Model, int64 Index_0);
	static class FString PurchasePages_GetNextUrl(const struct FOvrPurchasePages& Model);
	static int64 PurchasePages_GetSize(const struct FOvrPurchasePages& Model);
	static bool PurchasePages_HasNextPage(const struct FOvrPurchasePages& Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrPurchasePagesMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrPurchasePagesMethods")
	}
	static class UOvrPurchasePagesMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrPurchasePagesMethods>();
	}
};
DUMPER7_ASSERTS_UOvrPurchasePagesMethods;

// Class OVRPlatform.OvrApplicationInvitePagesMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrApplicationInvitePagesMethods final : public UObject
{
public:
	static struct FOvrApplicationInvite ApplicationInvitePages_GetElement(const struct FOvrApplicationInvitePages& Model, int64 Index_0);
	static class FString ApplicationInvitePages_GetNextUrl(const struct FOvrApplicationInvitePages& Model);
	static int64 ApplicationInvitePages_GetSize(const struct FOvrApplicationInvitePages& Model);
	static bool ApplicationInvitePages_HasNextPage(const struct FOvrApplicationInvitePages& Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrApplicationInvitePagesMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrApplicationInvitePagesMethods")
	}
	static class UOvrApplicationInvitePagesMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrApplicationInvitePagesMethods>();
	}
};
DUMPER7_ASSERTS_UOvrApplicationInvitePagesMethods;

// Class OVRPlatform.OvrChallengeEntryPagesMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrChallengeEntryPagesMethods final : public UObject
{
public:
	static struct FOvrChallengeEntry ChallengeEntryPages_GetElement(const struct FOvrChallengeEntryPages& Model, int64 Index_0);
	static class FString ChallengeEntryPages_GetNextUrl(const struct FOvrChallengeEntryPages& Model);
	static class FString ChallengeEntryPages_GetPreviousUrl(const struct FOvrChallengeEntryPages& Model);
	static int64 ChallengeEntryPages_GetSize(const struct FOvrChallengeEntryPages& Model);
	static int64 ChallengeEntryPages_GetTotalCount(const struct FOvrChallengeEntryPages& Model);
	static bool ChallengeEntryPages_HasNextPage(const struct FOvrChallengeEntryPages& Model);
	static bool ChallengeEntryPages_HasPreviousPage(const struct FOvrChallengeEntryPages& Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrChallengeEntryPagesMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrChallengeEntryPagesMethods")
	}
	static class UOvrChallengeEntryPagesMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrChallengeEntryPagesMethods>();
	}
};
DUMPER7_ASSERTS_UOvrChallengeEntryPagesMethods;

// Class OVRPlatform.OvrLeaderboardEntryPagesMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrLeaderboardEntryPagesMethods final : public UObject
{
public:
	static struct FOvrLeaderboardEntry LeaderboardEntryPages_GetElement(const struct FOvrLeaderboardEntryPages& Model, int64 Index_0);
	static class FString LeaderboardEntryPages_GetNextUrl(const struct FOvrLeaderboardEntryPages& Model);
	static class FString LeaderboardEntryPages_GetPreviousUrl(const struct FOvrLeaderboardEntryPages& Model);
	static int64 LeaderboardEntryPages_GetSize(const struct FOvrLeaderboardEntryPages& Model);
	static int64 LeaderboardEntryPages_GetTotalCount(const struct FOvrLeaderboardEntryPages& Model);
	static bool LeaderboardEntryPages_HasNextPage(const struct FOvrLeaderboardEntryPages& Model);
	static bool LeaderboardEntryPages_HasPreviousPage(const struct FOvrLeaderboardEntryPages& Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrLeaderboardEntryPagesMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrLeaderboardEntryPagesMethods")
	}
	static class UOvrLeaderboardEntryPagesMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrLeaderboardEntryPagesMethods>();
	}
};
DUMPER7_ASSERTS_UOvrLeaderboardEntryPagesMethods;

// Class OVRPlatform.OvrUserPagesMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrUserPagesMethods final : public UObject
{
public:
	static struct FOvrUser UserPages_GetElement(const struct FOvrUserPages& Model, int64 Index_0);
	static class FString UserPages_GetNextUrl(const struct FOvrUserPages& Model);
	static int64 UserPages_GetSize(const struct FOvrUserPages& Model);
	static bool UserPages_HasNextPage(const struct FOvrUserPages& Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrUserPagesMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrUserPagesMethods")
	}
	static class UOvrUserPagesMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrUserPagesMethods>();
	}
};
DUMPER7_ASSERTS_UOvrUserPagesMethods;

// Class OVRPlatform.OvrChallengePagesMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrChallengePagesMethods final : public UObject
{
public:
	static struct FOvrChallenge ChallengePages_GetElement(const struct FOvrChallengePages& Model, int64 Index_0);
	static class FString ChallengePages_GetNextUrl(const struct FOvrChallengePages& Model);
	static class FString ChallengePages_GetPreviousUrl(const struct FOvrChallengePages& Model);
	static int64 ChallengePages_GetSize(const struct FOvrChallengePages& Model);
	static int64 ChallengePages_GetTotalCount(const struct FOvrChallengePages& Model);
	static bool ChallengePages_HasNextPage(const struct FOvrChallengePages& Model);
	static bool ChallengePages_HasPreviousPage(const struct FOvrChallengePages& Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrChallengePagesMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrChallengePagesMethods")
	}
	static class UOvrChallengePagesMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrChallengePagesMethods>();
	}
};
DUMPER7_ASSERTS_UOvrChallengePagesMethods;

// Class OVRPlatform.OvrUserCapabilityPagesMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrUserCapabilityPagesMethods final : public UObject
{
public:
	static struct FOvrUserCapability UserCapabilityPages_GetElement(const struct FOvrUserCapabilityPages& Model, int64 Index_0);
	static class FString UserCapabilityPages_GetNextUrl(const struct FOvrUserCapabilityPages& Model);
	static int64 UserCapabilityPages_GetSize(const struct FOvrUserCapabilityPages& Model);
	static bool UserCapabilityPages_HasNextPage(const struct FOvrUserCapabilityPages& Model);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrUserCapabilityPagesMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrUserCapabilityPagesMethods")
	}
	static class UOvrUserCapabilityPagesMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrUserCapabilityPagesMethods>();
	}
};
DUMPER7_ASSERTS_UOvrUserCapabilityPagesMethods;

// Class OVRPlatform.OvrVoipDecoderMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrVoipDecoderMethods final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrVoipDecoderMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrVoipDecoderMethods")
	}
	static class UOvrVoipDecoderMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrVoipDecoderMethods>();
	}
};
DUMPER7_ASSERTS_UOvrVoipDecoderMethods;

// Class OVRPlatform.OvrVoipEncoderMethods
// 0x0000 (0x0028 - 0x0028)
class UOvrVoipEncoderMethods final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrVoipEncoderMethods")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrVoipEncoderMethods")
	}
	static class UOvrVoipEncoderMethods* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrVoipEncoderMethods>();
	}
};
DUMPER7_ASSERTS_UOvrVoipEncoderMethods;

// Class OVRPlatform.OvrPageRequestsBlueprintLibrary
// 0x0000 (0x0028 - 0x0028)
class UOvrPageRequestsBlueprintLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void FetchAchievementDefinitionPage(class UObject* WorldContextObject, const EOvrForwardArrayIteratorInputPins& InExecs, EOvrPageRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrAchievementDefinitionPages& AchievementDefinitionPages, TArray<struct FOvrAchievementDefinition>* AchievementDefinitionArray, bool* bHasNextPage, class FString* ErrorMsg);
	static void FetchAchievementProgressPage(class UObject* WorldContextObject, const EOvrForwardArrayIteratorInputPins& InExecs, EOvrPageRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrAchievementProgressPages& AchievementProgressPages, TArray<struct FOvrAchievementProgress>* AchievementProgressArray, bool* bHasNextPage, class FString* ErrorMsg);
	static void FetchApplicationInvitePage(class UObject* WorldContextObject, const EOvrForwardArrayIteratorInputPins& InExecs, EOvrPageRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrApplicationInvitePages& ApplicationInvitePages, TArray<struct FOvrApplicationInvite>* ApplicationInviteArray, bool* bHasNextPage, class FString* ErrorMsg);
	static void FetchBlockedUserPage(class UObject* WorldContextObject, const EOvrForwardArrayIteratorInputPins& InExecs, EOvrPageRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrBlockedUserPages& BlockedUserPages, TArray<struct FOvrBlockedUser>* BlockedUserArray, bool* bHasNextPage, class FString* ErrorMsg);
	static void FetchChallengeEntryPage(class UObject* WorldContextObject, const EOvrBidirectionalArrayIteratorInputPins& InExecs, EOvrPageRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrChallengeEntryPages& ChallengeEntryPages, TArray<struct FOvrChallengeEntry>* ChallengeEntryArray, bool* bHasNextPage, bool* bHasPreviousPage, class FString* ErrorMsg);
	static void FetchChallengePage(class UObject* WorldContextObject, const EOvrBidirectionalArrayIteratorInputPins& InExecs, EOvrPageRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrChallengePages& ChallengePages, TArray<struct FOvrChallenge>* ChallengeArray, bool* bHasNextPage, bool* bHasPreviousPage, class FString* ErrorMsg);
	static void FetchCowatchViewerPage(class UObject* WorldContextObject, const EOvrForwardArrayIteratorInputPins& InExecs, EOvrPageRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrCowatchViewerPages& CowatchViewerPages, TArray<struct FOvrCowatchViewer>* CowatchViewerArray, bool* bHasNextPage, class FString* ErrorMsg);
	static void FetchDestinationPage(class UObject* WorldContextObject, const EOvrForwardArrayIteratorInputPins& InExecs, EOvrPageRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrDestinationPages& DestinationPages, TArray<struct FOvrDestination>* DestinationArray, bool* bHasNextPage, class FString* ErrorMsg);
	static void FetchLeaderboardEntryPage(class UObject* WorldContextObject, const EOvrBidirectionalArrayIteratorInputPins& InExecs, EOvrPageRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrLeaderboardEntryPages& LeaderboardEntryPages, TArray<struct FOvrLeaderboardEntry>* LeaderboardEntryArray, bool* bHasNextPage, bool* bHasPreviousPage, class FString* ErrorMsg);
	static void FetchLeaderboardPage(class UObject* WorldContextObject, const EOvrForwardArrayIteratorInputPins& InExecs, EOvrPageRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrLeaderboardPages& LeaderboardPages, TArray<struct FOvrLeaderboard>* LeaderboardArray, bool* bHasNextPage, class FString* ErrorMsg);
	static void FetchProductPage(class UObject* WorldContextObject, const EOvrForwardArrayIteratorInputPins& InExecs, EOvrPageRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrProductPages& ProductPages, TArray<struct FOvrProduct>* ProductArray, bool* bHasNextPage, class FString* ErrorMsg);
	static void FetchPurchasePage(class UObject* WorldContextObject, const EOvrForwardArrayIteratorInputPins& InExecs, EOvrPageRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrPurchasePages& PurchasePages, TArray<struct FOvrPurchase>* PurchaseArray, bool* bHasNextPage, class FString* ErrorMsg);
	static void FetchUserCapabilityPage(class UObject* WorldContextObject, const EOvrForwardArrayIteratorInputPins& InExecs, EOvrPageRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrUserCapabilityPages& UserCapabilityPages, TArray<struct FOvrUserCapability>* UserCapabilityArray, bool* bHasNextPage, class FString* ErrorMsg);
	static void FetchUserPage(class UObject* WorldContextObject, const EOvrForwardArrayIteratorInputPins& InExecs, EOvrPageRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrUserPages& UserPages, TArray<struct FOvrUser>* UserArray, bool* bHasNextPage, class FString* ErrorMsg);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrPageRequestsBlueprintLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrPageRequestsBlueprintLibrary")
	}
	static class UOvrPageRequestsBlueprintLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrPageRequestsBlueprintLibrary>();
	}
};
DUMPER7_ASSERTS_UOvrPageRequestsBlueprintLibrary;

// Class OVRPlatform.OvrRequestsBlueprintLibrary
// 0x0000 (0x0028 - 0x0028)
class UOvrRequestsBlueprintLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void AbuseReport_ReportRequestHandled(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, EOvrReportRequestResponse Response, class FString* ErrorMsg);
	static void Achievements_AddCount(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& Name_0, int64 Count, struct FOvrAchievementUpdate* AchievementUpdate, class FString* ErrorMsg);
	static void Achievements_AddFields(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& Name_0, const class FString& Fields, struct FOvrAchievementUpdate* AchievementUpdate, class FString* ErrorMsg);
	static void Achievements_GetAllDefinitions(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrAchievementDefinitionPages* AchievementDefinitionPages, class FString* ErrorMsg);
	static void Achievements_GetAllProgress(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrAchievementProgressPages* AchievementProgressPages, class FString* ErrorMsg);
	static void Achievements_GetDefinitionsByName(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const TArray<class FString>& Names, struct FOvrAchievementDefinitionPages* AchievementDefinitionPages, class FString* ErrorMsg);
	static void Achievements_GetProgressByName(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const TArray<class FString>& Names, struct FOvrAchievementProgressPages* AchievementProgressPages, class FString* ErrorMsg);
	static void Achievements_Unlock(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& Name_0, struct FOvrAchievementUpdate* AchievementUpdate, class FString* ErrorMsg);
	static void Application_CancelAppDownload(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrAppDownloadResult* AppDownloadResult, class FString* ErrorMsg);
	static void Application_CheckAppDownloadProgress(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrAppDownloadProgressResult* AppDownloadProgressResult, class FString* ErrorMsg);
	static void Application_GetVersion(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrApplicationVersion* ApplicationVersion, class FString* ErrorMsg);
	static void Application_InstallAppUpdateAndRelaunch(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrApplicationOptions& DeeplinkOptions, struct FOvrAppDownloadResult* AppDownloadResult, class FString* ErrorMsg);
	static void Application_LaunchOtherApp(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& AppID, const struct FOvrApplicationOptions& DeeplinkOptions, class FString* StringPayload, class FString* ErrorMsg);
	static void Application_StartAppDownload(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrAppDownloadResult* AppDownloadResult, class FString* ErrorMsg);
	static void AssetFile_Delete(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& AssetFileId, struct FOvrAssetFileDeleteResult* AssetFileDeleteResult, class FString* ErrorMsg);
	static void AssetFile_DeleteById(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& AssetFileId, struct FOvrAssetFileDeleteResult* AssetFileDeleteResult, class FString* ErrorMsg);
	static void AssetFile_DeleteByName(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& AssetFileName, struct FOvrAssetFileDeleteResult* AssetFileDeleteResult, class FString* ErrorMsg);
	static void AssetFile_Download(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& AssetFileId, struct FOvrAssetFileDownloadResult* AssetFileDownloadResult, class FString* ErrorMsg);
	static void AssetFile_DownloadById(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& AssetFileId, struct FOvrAssetFileDownloadResult* AssetFileDownloadResult, class FString* ErrorMsg);
	static void AssetFile_DownloadByName(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& AssetFileName, struct FOvrAssetFileDownloadResult* AssetFileDownloadResult, class FString* ErrorMsg);
	static void AssetFile_DownloadCancel(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& AssetFileId, struct FOvrAssetFileDownloadCancelResult* AssetFileDownloadCancelResult, class FString* ErrorMsg);
	static void AssetFile_DownloadCancelById(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& AssetFileId, struct FOvrAssetFileDownloadCancelResult* AssetFileDownloadCancelResult, class FString* ErrorMsg);
	static void AssetFile_DownloadCancelByName(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& AssetFileName, struct FOvrAssetFileDownloadCancelResult* AssetFileDownloadCancelResult, class FString* ErrorMsg);
	static void AssetFile_GetList(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, TArray<struct FOvrAssetDetails>* AssetDetailsArray, class FString* ErrorMsg);
	static void AssetFile_Status(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& AssetFileId, struct FOvrAssetDetails* AssetDetails, class FString* ErrorMsg);
	static void AssetFile_StatusById(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& AssetFileId, struct FOvrAssetDetails* AssetDetails, class FString* ErrorMsg);
	static void AssetFile_StatusByName(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& AssetFileName, struct FOvrAssetDetails* AssetDetails, class FString* ErrorMsg);
	static void Avatar_LaunchAvatarEditor(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrAvatarEditorOptions& Options, struct FOvrAvatarEditorResult* AvatarEditorResult, class FString* ErrorMsg);
	static void Challenges_Create(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& LeaderboardName, const struct FOvrChallengeOptions& ChallengeOptions, struct FOvrChallenge* Challenge, class FString* ErrorMsg);
	static void Challenges_DeclineInvite(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& ChallengeID, struct FOvrChallenge* Challenge, class FString* ErrorMsg);
	static void Challenges_Delete(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& ChallengeID, class FString* ErrorMsg);
	static void Challenges_Get(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& ChallengeID, struct FOvrChallenge* Challenge, class FString* ErrorMsg);
	static void Challenges_GetEntries(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& ChallengeID, int32 Limit, EOvrLeaderboardFilterType Filter, EOvrLeaderboardStartAt StartAt, struct FOvrChallengeEntryPages* ChallengeEntryPages, class FString* ErrorMsg);
	static void Challenges_GetEntriesAfterRank(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& ChallengeID, int32 Limit, int64 AfterRank, struct FOvrChallengeEntryPages* ChallengeEntryPages, class FString* ErrorMsg);
	static void Challenges_GetEntriesByIds(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& ChallengeID, int32 Limit, EOvrLeaderboardStartAt StartAt, const TArray<struct FOvrId>& UserIds, struct FOvrChallengeEntryPages* ChallengeEntryPages, class FString* ErrorMsg);
	static void Challenges_GetList(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrChallengeOptions& ChallengeOptions, int32 Limit, struct FOvrChallengePages* ChallengePages, class FString* ErrorMsg);
	static void Challenges_Join(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& ChallengeID, struct FOvrChallenge* Challenge, class FString* ErrorMsg);
	static void Challenges_Leave(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& ChallengeID, struct FOvrChallenge* Challenge, class FString* ErrorMsg);
	static void Challenges_UpdateInfo(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& ChallengeID, const struct FOvrChallengeOptions& ChallengeOptions, struct FOvrChallenge* Challenge, class FString* ErrorMsg);
	static void Cowatching_GetPresenterData(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, class FString* StringPayload, class FString* ErrorMsg);
	static void Cowatching_GetViewersData(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrCowatchViewerPages* CowatchViewerPages, class FString* ErrorMsg);
	static void Cowatching_IsInSession(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrCowatchingState* CowatchingState, class FString* ErrorMsg);
	static void Cowatching_JoinSession(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, class FString* ErrorMsg);
	static void Cowatching_LaunchInviteDialog(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, class FString* ErrorMsg);
	static void Cowatching_LeaveSession(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, class FString* ErrorMsg);
	static void Cowatching_RequestToPresent(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, class FString* ErrorMsg);
	static void Cowatching_ResignFromPresenting(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, class FString* ErrorMsg);
	static void Cowatching_SetPresenterData(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& VideoTitle, const class FString& PresenterData, class FString* ErrorMsg);
	static void Cowatching_SetViewerData(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& ViewerData, class FString* ErrorMsg);
	static void DeviceApplicationIntegrity_GetIntegrityToken(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& ChallengeNonce, class FString* StringPayload, class FString* ErrorMsg);
	static void Entitlement_GetIsViewerEntitled(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, class FString* ErrorMsg);
	static void GroupPresence_Clear(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, class FString* ErrorMsg);
	static void GroupPresence_GetInvitableUsers(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrInviteOptions& Options, struct FOvrUserPages* UserPages, class FString* ErrorMsg);
	static void GroupPresence_GetSentInvites(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrApplicationInvitePages* ApplicationInvitePages, class FString* ErrorMsg);
	static void GroupPresence_LaunchInvitePanel(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrInviteOptions& Options, struct FOvrInvitePanelResultInfo* InvitePanelResultInfo, class FString* ErrorMsg);
	static void GroupPresence_LaunchMultiplayerErrorDialog(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrMultiplayerErrorOptions& Options, class FString* ErrorMsg);
	static void GroupPresence_LaunchRejoinDialog(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& LobbySessionId, const class FString& MatchSessionId, const class FString& DestinationApiName, struct FOvrRejoinDialogResult* RejoinDialogResult, class FString* ErrorMsg);
	static void GroupPresence_LaunchRosterPanel(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrRosterOptions& Options, class FString* ErrorMsg);
	static void GroupPresence_SendInvites(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const TArray<struct FOvrId>& UserIds, struct FOvrSendInvitesResult* SendInvitesResult, class FString* ErrorMsg);
	static void GroupPresence_Set(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrGroupPresenceOptions& GroupPresenceOptions, class FString* ErrorMsg);
	static void GroupPresence_SetDeeplinkMessageOverride(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& DeeplinkMessage, class FString* ErrorMsg);
	static void GroupPresence_SetDestination(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& ApiName, class FString* ErrorMsg);
	static void GroupPresence_SetIsJoinable(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, bool IsJoinable, class FString* ErrorMsg);
	static void GroupPresence_SetLobbySession(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& ID, class FString* ErrorMsg);
	static void GroupPresence_SetMatchSession(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& ID, class FString* ErrorMsg);
	static void IAP_ConsumePurchase(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& SKU, class FString* ErrorMsg);
	static void IAP_GetProductsBySKU(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const TArray<class FString>& Skus, struct FOvrProductPages* ProductPages, class FString* ErrorMsg);
	static void IAP_GetViewerPurchases(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrPurchasePages* PurchasePages, class FString* ErrorMsg);
	static void IAP_GetViewerPurchasesDurableCache(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrPurchasePages* PurchasePages, class FString* ErrorMsg);
	static void IAP_LaunchCheckoutFlow(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& SKU, struct FOvrPurchase* Purchase, class FString* ErrorMsg);
	static void LanguagePack_GetCurrent(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrAssetDetails* AssetDetails, class FString* ErrorMsg);
	static void LanguagePack_SetCurrent(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& Tag, struct FOvrAssetFileDownloadResult* AssetFileDownloadResult, class FString* ErrorMsg);
	static void Leaderboard_Get(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& LeaderboardName, struct FOvrLeaderboardPages* LeaderboardPages, class FString* ErrorMsg);
	static void Leaderboard_GetEntries(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& LeaderboardName, int32 Limit, EOvrLeaderboardFilterType Filter, EOvrLeaderboardStartAt StartAt, struct FOvrLeaderboardEntryPages* LeaderboardEntryPages, class FString* ErrorMsg);
	static void Leaderboard_GetEntriesAfterRank(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& LeaderboardName, int32 Limit, int64 AfterRank, struct FOvrLeaderboardEntryPages* LeaderboardEntryPages, class FString* ErrorMsg);
	static void Leaderboard_GetEntriesByIds(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& LeaderboardName, int32 Limit, EOvrLeaderboardStartAt StartAt, const TArray<struct FOvrId>& UserIds, struct FOvrLeaderboardEntryPages* LeaderboardEntryPages, class FString* ErrorMsg);
	static void Leaderboard_WriteEntry(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& LeaderboardName, int64 Score, const TArray<uint8>& ExtraData, bool ForceUpdate, struct FOvrLeaderboardUpdateStatus* LeaderboardUpdateStatus, class FString* ErrorMsg);
	static void Leaderboard_WriteEntryWithSupplementaryMetric(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& LeaderboardName, int64 Score, int64 SupplementaryMetric, const TArray<uint8>& ExtraData, bool ForceUpdate, struct FOvrLeaderboardUpdateStatus* LeaderboardUpdateStatus, class FString* ErrorMsg);
	static void Media_ShareToFacebook(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const class FString& PostTextSuggestion, const class FString& FilePath, EOvrMediaContentType ContentType, struct FOvrShareMediaResult* ShareMediaResult, class FString* ErrorMsg);
	static void Notification_MarkAsRead(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& NotificationId, class FString* ErrorMsg);
	static void Party_GetCurrent(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrParty* Party, class FString* ErrorMsg);
	static void RichPresence_Clear(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, class FString* ErrorMsg);
	static void RichPresence_GetDestinations(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrDestinationPages* DestinationPages, class FString* ErrorMsg);
	static void RichPresence_Set(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrRichPresenceOptions& RichPresenceOptions, class FString* ErrorMsg);
	static void User_Get(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& UserId, struct FOvrUser* User, class FString* ErrorMsg);
	static void User_GetAccessToken(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, class FString* StringPayload, class FString* ErrorMsg);
	static void User_GetBlockedUsers(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrBlockedUserPages* BlockedUserPages, class FString* ErrorMsg);
	static void User_GetLoggedInUser(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrUser* User, class FString* ErrorMsg);
	static void User_GetLoggedInUserFriends(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrUserPages* UserPages, class FString* ErrorMsg);
	static void User_GetOrgScopedID(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& UserId, struct FOvrOrgScopedID* OrgScopedID, class FString* ErrorMsg);
	static void User_GetSdkAccounts(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, TArray<struct FOvrSdkAccount>* SdkAccountArray, class FString* ErrorMsg);
	static void User_GetUserProof(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrUserProof* UserProof, class FString* ErrorMsg);
	static void User_LaunchBlockFlow(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& UserId, struct FOvrLaunchBlockFlowResult* LaunchBlockFlowResult, class FString* ErrorMsg);
	static void User_LaunchFriendRequestFlow(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& UserId, struct FOvrLaunchFriendRequestFlowResult* LaunchFriendRequestFlowResult, class FString* ErrorMsg);
	static void User_LaunchUnblockFlow(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, const struct FOvrId& UserId, struct FOvrLaunchUnblockFlowResult* LaunchUnblockFlowResult, class FString* ErrorMsg);
	static void UserAgeCategory_Get(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrUserAccountAgeCategory* UserAccountAgeCategory, class FString* ErrorMsg);
	static void UserAgeCategory_Report(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, EOvrAppAgeCategory AgeCategory, class FString* ErrorMsg);
	static void Voip_GetMicrophoneAvailability(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, struct FOvrMicrophoneAvailabilityState* MicrophoneAvailabilityState, class FString* ErrorMsg);
	static void Voip_SetSystemVoipSuppressed(class UObject* WorldContextObject, EOvrRequestOutputPins* OutExecs, const struct FLatentActionInfo& LatentInfo, bool Suppressed, struct FOvrSystemVoipState* SystemVoipState, class FString* ErrorMsg);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrRequestsBlueprintLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrRequestsBlueprintLibrary")
	}
	static class UOvrRequestsBlueprintLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrRequestsBlueprintLibrary>();
	}
};
DUMPER7_ASSERTS_UOvrRequestsBlueprintLibrary;

// Class OVRPlatform.OvrPlatformSubsystem
// 0x02E8 (0x0318 - 0x0030)
class UOvrPlatformSubsystem final : public UGameInstanceSubsystem
{
public:
	uint8                                         Pad_30[0x18];                                      // 0x0030(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(const class FString& ReportButtonPressed)> OnAbuseReportReportButtonPressed; // 0x0048(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FString& LaunchIntentChanged)> OnApplicationLifecycleLaunchIntentChanged; // 0x0058(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FOvrAssetFileDownloadUpdate& DownloadUpdate)> OnAssetFileDownloadUpdate; // 0x0068(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FString& ApiNotReady)> OnCowatchingApiNotReady;        // 0x0078(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FString& ApiReady)> OnCowatchingApiReady;              // 0x0088(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FOvrCowatchingState& InSessionChanged)> OnCowatchingInSessionChanged; // 0x0098(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FString& Initialized)> OnCowatchingInitialized;        // 0x00A8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FString& PresenterDataChanged)> OnCowatchingPresenterDataChanged; // 0x00B8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FString& SessionStarted)> OnCowatchingSessionStarted;  // 0x00C8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FString& SessionStopped)> OnCowatchingSessionStopped;  // 0x00D8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FOvrCowatchViewerUpdate& ViewersDataChanged)> OnCowatchingViewersDataChanged; // 0x00E8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FOvrLaunchInvitePanelFlowResult& InvitationsSent)> OnGroupPresenceInvitationsSent; // 0x00F8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FOvrGroupPresenceJoinIntent& JoinIntentReceived)> OnGroupPresenceJoinIntentReceived; // 0x0108(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FOvrGroupPresenceLeaveIntent& LeaveIntentReceived)> OnGroupPresenceLeaveIntentReceived; // 0x0118(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FOvrHttpTransferUpdate& Transfer)> OnHTTPTransfer;    // 0x0128(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FOvrLivestreamingStatus& StatusChange)> OnLivestreamingStatusChange; // 0x0138(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FOvrNetSyncConnection& ConnectionStatusChanged)> OnNetSyncConnectionStatusChanged; // 0x0148(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FOvrNetSyncSessionsChangedNotification& SessionsChanged)> OnNetSyncSessionsChanged; // 0x0158(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FOvrPartyUpdateNotification& PartyUpdate)> OnPartyPartyUpdate; // 0x0168(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FString& MicrophoneAvailabilityStateUpdate)> OnVoipMicrophoneAvailabilityStateUpdate; // 0x0178(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const struct FOvrSystemVoipState& SystemVoipState)> OnVoipSystemVoipState; // 0x0188(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FString& GetDataChannelMessageUpdate)> OnVrcameraGetDataChannelMessageUpdate; // 0x0198(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FString& GetSurfaceUpdate)> OnVrcameraGetSurfaceUpdate; // 0x01A8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_1B8[0x160];                                    // 0x01B8(0x0160)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void StartMessagePump();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrPlatformSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrPlatformSubsystem")
	}
	static class UOvrPlatformSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrPlatformSubsystem>();
	}
};
DUMPER7_ASSERTS_UOvrPlatformSubsystem;

// Class OVRPlatform.OvrPlatformUtilsLibrary
// 0x0000 (0x0028 - 0x0028)
class UOvrPlatformUtilsLibrary final : public UBlueprintFunctionLibrary
{
public:
	static struct FOvrId Conv_Int64ToOvrId(int64 ID);
	static class FString Conv_OvrIdToString(const struct FOvrId& ID);
	static bool EqualEqual_OvrIdOvrId(const struct FOvrId& A, const struct FOvrId& B);
	static class FString MakeRandomSessionId(const class FString& Prefix);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OvrPlatformUtilsLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OvrPlatformUtilsLibrary")
	}
	static class UOvrPlatformUtilsLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOvrPlatformUtilsLibrary>();
	}
};
DUMPER7_ASSERTS_UOvrPlatformUtilsLibrary;

SDK_NAMESPACE_END
