#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RotationGizmo

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "A2_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass RotationGizmo.RotationGizmo_C
// 0x0040 (0x0300 - 0x02C0)
class ARotationGizmo_C final : public ALevelEditorRotationGizmo
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   RotationGizmoBlender_Z_Display;                    // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   RotationGizmoBlender_Z_Axis;                       // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   RotationGizmoBlender_Y_Display;                    // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   RotationGizmoBlender_Y_Axis;                       // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   RotationGizmoBlender_X_Display;                    // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   RotationGizmoBlender_X_Axis;                       // 0x02F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_RotationGizmo(int32 EntryPoint);
	void LevelEditorComponentSpawned(class UActorComponent* ActorComponent);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RotationGizmo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RotationGizmo_C")
	}
	static class ARotationGizmo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARotationGizmo_C>();
	}
};
DUMPER7_ASSERTS_ARotationGizmo_C;

SDK_NAMESPACE_END
