#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SandboxEngine

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SandboxEngine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function SandboxEngine.LuauBehavior.IsNetworkReady
// 0x0001 (0x0001 - 0x0000)
struct LuauBehavior_IsNetworkReady final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_LuauBehavior_IsNetworkReady;

// Function SandboxEngine.A2Object.GetGamePosition
// 0x0018 (0x0018 - 0x0000)
struct A2Object_GetGamePosition final
{
public:
	struct FVector                                ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_A2Object_GetGamePosition;

// Function SandboxEngine.GamemodesManager.GetGameMode
// 0x0020 (0x0020 - 0x0000)
struct GamemodesManager_GetGameMode final
{
public:
	class UWorld*                                 World;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 SlotID;                                            // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UModuleStateExternalLuaAPI*             ReturnValue;                                       // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_GamemodesManager_GetGameMode;

// Function SandboxEngine.GamemodesManager.AddSlot
// 0x0008 (0x0008 - 0x0000)
struct GamemodesManager_AddSlot final
{
public:
	class AModuleSlot*                            GamemodeSlot;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_GamemodesManager_AddSlot;

// Function SandboxEngine.GamemodesManager.GetModuleSlotFromID
// 0x0020 (0x0020 - 0x0000)
struct GamemodesManager_GetModuleSlotFromID final
{
public:
	const class UObject*                          WorldContextObject;                                // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ID;                                                // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AModuleSlot*                            ReturnValue;                                       // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_GamemodesManager_GetModuleSlotFromID;

// Function SandboxEngine.LE_ComponentGenerator.BindCallbackEvent_Actor
// 0x0010 (0x0010 - 0x0000)
struct LE_ComponentGenerator_BindCallbackEvent_Actor final
{
public:
	class AActor*                                 Object;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   FunctionName;                                      // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_LE_ComponentGenerator_BindCallbackEvent_Actor;

// Function SandboxEngine.LE_ComponentGenerator.Blueprint_BindCallbackEvent
// 0x0018 (0x0018 - 0x0000)
struct LE_ComponentGenerator_Blueprint_BindCallbackEvent final
{
public:
	class FName                                   UFunctionOrEventName;                              // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 UserFacingName;                                    // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_LE_ComponentGenerator_Blueprint_BindCallbackEvent;

// Function SandboxEngine.ModuleSlot.GenerateUniqueSlotID
// 0x0008 (0x0008 - 0x0000)
struct ModuleSlot_GenerateUniqueSlotID final
{
public:
	class FName                                   SlotPrefix;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleSlot_GenerateUniqueSlotID;

// Function SandboxEngine.ModuleSlot.LuauGetTransform
// 0x0060 (0x0060 - 0x0000)
struct ModuleSlot_LuauGetTransform final
{
public:
	struct FTransform                             ReturnValue;                                       // 0x0000(0x0060)(Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleSlot_LuauGetTransform;

// Function SandboxEngine.ModuleSlot.OnTeamColorsChangedModuleSlotEvent
// 0x0010 (0x0010 - 0x0000)
struct ModuleSlot_OnTeamColorsChangedModuleSlotEvent final
{
public:
	TArray<struct FTeamColor>                     Colors;                                            // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleSlot_OnTeamColorsChangedModuleSlotEvent;

// Function SandboxEngine.ModuleState.GetGamemodeBoolVariable
// 0x0018 (0x0018 - 0x0000)
struct ModuleState_GetGamemodeBoolVariable final
{
public:
	class FName                                   VariableName;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          FoundVariable;                                     // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBoolNetVar*                            ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_GetGamemodeBoolVariable;

// Function SandboxEngine.ModuleState.GetGamemodeFloatVariable
// 0x0018 (0x0018 - 0x0000)
struct ModuleState_GetGamemodeFloatVariable final
{
public:
	class FName                                   VariableName;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          FoundVariable;                                     // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UNumberNetVar*                          ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_GetGamemodeFloatVariable;

// Function SandboxEngine.ModuleState.GetGamemodeStringVariable
// 0x0018 (0x0018 - 0x0000)
struct ModuleState_GetGamemodeStringVariable final
{
public:
	class FName                                   VariableName;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          FoundVariable;                                     // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStringNetVar*                          ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_GetGamemodeStringVariable;

// Function SandboxEngine.ModuleState.GetIsGameRunning
// 0x0001 (0x0001 - 0x0000)
struct ModuleState_GetIsGameRunning final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_GetIsGameRunning;

// Function SandboxEngine.ModuleState.GetRoundsWon
// 0x0008 (0x0008 - 0x0000)
struct ModuleState_GetRoundsWon final
{
public:
	int32                                         Team;                                              // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_GetRoundsWon;

// Function SandboxEngine.ModuleState.GetScore
// 0x0008 (0x0008 - 0x0000)
struct ModuleState_GetScore final
{
public:
	int32                                         Team;                                              // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_GetScore;

// Function SandboxEngine.ModuleState.OnVariablesReady
// 0x0010 (0x0010 - 0x0000)
struct ModuleState_OnVariablesReady final
{
public:
	TDelegate<void(class UObjectNetVar* Variables)> Callback;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_OnVariablesReady;

// Function SandboxEngine.ModuleState.SetupDefaultVariables
// 0x0010 (0x0010 - 0x0000)
struct ModuleState_SetupDefaultVariables final
{
public:
	TDelegate<void(class UObjectNetVar* Variables)> Callback;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_SetupDefaultVariables;

// Function SandboxEngine.ModuleState.SubscribeGeneralEventMulticastBool
// 0x0018 (0x0018 - 0x0000)
struct ModuleState_SubscribeGeneralEventMulticastBool final
{
public:
	class FName                                   EventName;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(bool Value)>                   EventDelegate;                                     // 0x0008(0x0010)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_SubscribeGeneralEventMulticastBool;

// Function SandboxEngine.ModuleState.SubscribeGeneralEventMulticastNumber
// 0x0018 (0x0018 - 0x0000)
struct ModuleState_SubscribeGeneralEventMulticastNumber final
{
public:
	class FName                                   EventName;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(float Value)>                  ScoreChangedDelegate;                              // 0x0008(0x0010)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_SubscribeGeneralEventMulticastNumber;

// Function SandboxEngine.ModuleState.SubscribeGeneralEventMulticastString
// 0x0018 (0x0018 - 0x0000)
struct ModuleState_SubscribeGeneralEventMulticastString final
{
public:
	class FName                                   EventName;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(const class FString& Value)>   ScoreChangedDelegate;                              // 0x0008(0x0010)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_SubscribeGeneralEventMulticastString;

// Function SandboxEngine.ModuleState.SubscribeGeneralEventMulticastVoid
// 0x0018 (0x0018 - 0x0000)
struct ModuleState_SubscribeGeneralEventMulticastVoid final
{
public:
	class FName                                   EventName;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void()>                             ScoreChangedDelegate;                              // 0x0008(0x0010)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_SubscribeGeneralEventMulticastVoid;

// Function SandboxEngine.ModuleState.SubscribeGeneralEventServerBool
// 0x0018 (0x0018 - 0x0000)
struct ModuleState_SubscribeGeneralEventServerBool final
{
public:
	class FName                                   EventName;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(bool Value)>                   EventDelegate;                                     // 0x0008(0x0010)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_SubscribeGeneralEventServerBool;

// Function SandboxEngine.ModuleState.SubscribeGeneralEventServerNumber
// 0x0018 (0x0018 - 0x0000)
struct ModuleState_SubscribeGeneralEventServerNumber final
{
public:
	class FName                                   EventName;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(float Value)>                  ScoreChangedDelegate;                              // 0x0008(0x0010)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_SubscribeGeneralEventServerNumber;

// Function SandboxEngine.ModuleState.SubscribeGeneralEventServerString
// 0x0018 (0x0018 - 0x0000)
struct ModuleState_SubscribeGeneralEventServerString final
{
public:
	class FName                                   EventName;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(const class FString& Value)>   ScoreChangedDelegate;                              // 0x0008(0x0010)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_SubscribeGeneralEventServerString;

// Function SandboxEngine.ModuleState.SubscribeGeneralEventServerVoid
// 0x0018 (0x0018 - 0x0000)
struct ModuleState_SubscribeGeneralEventServerVoid final
{
public:
	class FName                                   EventName;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void()>                             ScoreChangedDelegate;                              // 0x0008(0x0010)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_SubscribeGeneralEventServerVoid;

// Function SandboxEngine.ModuleState.SubscribeRoundsWonChanged
// 0x0010 (0x0010 - 0x0000)
struct ModuleState_SubscribeRoundsWonChanged final
{
public:
	TDelegate<void(int32 Team, int32 Rounds)>     RoundsWonChangedDelegate;                          // 0x0000(0x0010)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_SubscribeRoundsWonChanged;

// Function SandboxEngine.ModuleState.SubscribeScoreChanged
// 0x0010 (0x0010 - 0x0000)
struct ModuleState_SubscribeScoreChanged final
{
public:
	TDelegate<void(int32 Team, int32 Score)>      ScoreChangedDelegate;                              // 0x0000(0x0010)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_SubscribeScoreChanged;

// Function SandboxEngine.ModuleState.SubscribeTeamRoundsWonChanged
// 0x0014 (0x0014 - 0x0000)
struct ModuleState_SubscribeTeamRoundsWonChanged final
{
public:
	int32                                         TeamID;                                            // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(int32 Rounds)>                 TeamRoundsWonChangedDelegate;                      // 0x0004(0x0010)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_SubscribeTeamRoundsWonChanged;

// Function SandboxEngine.ModuleState.SubscribeTeamScoreChanged
// 0x0014 (0x0014 - 0x0000)
struct ModuleState_SubscribeTeamScoreChanged final
{
public:
	int32                                         TeamID;                                            // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(int32 Score)>                  TeamScoreChangedDelegate;                          // 0x0004(0x0010)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleState_SubscribeTeamScoreChanged;

// Function SandboxEngine.ModuleStateExternalLuaAPI.GetBoolConfigVariable
// 0x0018 (0x0018 - 0x0000)
struct ModuleStateExternalLuaAPI_GetBoolConfigVariable final
{
public:
	class FString                                 VariableName;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_ModuleStateExternalLuaAPI_GetBoolConfigVariable;

// Function SandboxEngine.ModuleStateExternalLuaAPI.GetNumberConfigVariable
// 0x0018 (0x0018 - 0x0000)
struct ModuleStateExternalLuaAPI_GetNumberConfigVariable final
{
public:
	class FString                                 VariableName;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ReturnValue;                                       // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_ModuleStateExternalLuaAPI_GetNumberConfigVariable;

// Function SandboxEngine.ModuleStateExternalLuaAPI.GetStringConfigVariable
// 0x0020 (0x0020 - 0x0000)
struct ModuleStateExternalLuaAPI_GetStringConfigVariable final
{
public:
	class FString                                 VariableName;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleStateExternalLuaAPI_GetStringConfigVariable;

// Function SandboxEngine.ModuleStateExternalLuaAPI.GetTeamRoundsWon
// 0x0008 (0x0008 - 0x0000)
struct ModuleStateExternalLuaAPI_GetTeamRoundsWon final
{
public:
	int32                                         TeamNum;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleStateExternalLuaAPI_GetTeamRoundsWon;

// Function SandboxEngine.ModuleStateExternalLuaAPI.GetTeamScore
// 0x0008 (0x0008 - 0x0000)
struct ModuleStateExternalLuaAPI_GetTeamScore final
{
public:
	float                                         TeamNum;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleStateExternalLuaAPI_GetTeamScore;

// Function SandboxEngine.ModuleStateExternalLuaAPI.SetBoolConfigVariable
// 0x0018 (0x0018 - 0x0000)
struct ModuleStateExternalLuaAPI_SetBoolConfigVariable final
{
public:
	class FString                                 VariableName;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Value;                                             // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_ModuleStateExternalLuaAPI_SetBoolConfigVariable;

// Function SandboxEngine.ModuleStateExternalLuaAPI.SetNumberConfigVariable
// 0x0018 (0x0018 - 0x0000)
struct ModuleStateExternalLuaAPI_SetNumberConfigVariable final
{
public:
	class FString                                 VariableName;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Value;                                             // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_ModuleStateExternalLuaAPI_SetNumberConfigVariable;

// Function SandboxEngine.ModuleStateExternalLuaAPI.SetStringConfigVariable
// 0x0020 (0x0020 - 0x0000)
struct ModuleStateExternalLuaAPI_SetStringConfigVariable final
{
public:
	class FString                                 VariableName;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Value;                                             // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleStateExternalLuaAPI_SetStringConfigVariable;

// Function SandboxEngine.ModuleStateLuaAPI.LUA_GenerateDeclaration
// 0x0010 (0x0010 - 0x0000)
struct ModuleStateLuaAPI_LUA_GenerateDeclaration final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_LUA_GenerateDeclaration;

// Function SandboxEngine.ModuleStateLuaAPI.BroadcastEvent
// 0x0010 (0x0010 - 0x0000)
struct ModuleStateLuaAPI_BroadcastEvent final
{
public:
	class FString                                 EventName;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_BroadcastEvent;

// Function SandboxEngine.ModuleStateLuaAPI.BroadcastEventBool
// 0x0018 (0x0018 - 0x0000)
struct ModuleStateLuaAPI_BroadcastEventBool final
{
public:
	class FString                                 EventName;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Value;                                             // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_BroadcastEventBool;

// Function SandboxEngine.ModuleStateLuaAPI.BroadcastEventNumber
// 0x0018 (0x0018 - 0x0000)
struct ModuleStateLuaAPI_BroadcastEventNumber final
{
public:
	class FString                                 EventName;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Value;                                             // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_BroadcastEventNumber;

// Function SandboxEngine.ModuleStateLuaAPI.BroadcastEventString
// 0x0020 (0x0020 - 0x0000)
struct ModuleStateLuaAPI_BroadcastEventString final
{
public:
	class FString                                 EventName;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 String;                                            // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_BroadcastEventString;

// Function SandboxEngine.ModuleStateLuaAPI.EmitStatEventForAllPlayers
// 0x0018 (0x0018 - 0x0000)
struct ModuleStateLuaAPI_EmitStatEventForAllPlayers final
{
public:
	class FString                                 String;                                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         I;                                                 // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_EmitStatEventForAllPlayers;

// Function SandboxEngine.ModuleStateLuaAPI.EmitStatEventForAllPlayersOnTeam
// 0x0020 (0x0020 - 0x0000)
struct ModuleStateLuaAPI_EmitStatEventForAllPlayersOnTeam final
{
public:
	int32                                         TeamIndex;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 String;                                            // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         I;                                                 // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_EmitStatEventForAllPlayersOnTeam;

// Function SandboxEngine.ModuleStateLuaAPI.GetBoolConfigVariable
// 0x0018 (0x0018 - 0x0000)
struct ModuleStateLuaAPI_GetBoolConfigVariable final
{
public:
	class FString                                 EventName;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_GetBoolConfigVariable;

// Function SandboxEngine.ModuleStateLuaAPI.GetNumberConfigVariable
// 0x0018 (0x0018 - 0x0000)
struct ModuleStateLuaAPI_GetNumberConfigVariable final
{
public:
	class FString                                 EventName;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ReturnValue;                                       // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_GetNumberConfigVariable;

// Function SandboxEngine.ModuleStateLuaAPI.GetStringConfigVariable
// 0x0020 (0x0020 - 0x0000)
struct ModuleStateLuaAPI_GetStringConfigVariable final
{
public:
	class FString                                 EventName;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_GetStringConfigVariable;

// Function SandboxEngine.ModuleStateLuaAPI.SetBoolVariable
// 0x0018 (0x0018 - 0x0000)
struct ModuleStateLuaAPI_SetBoolVariable final
{
public:
	class FString                                 EventName;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Value;                                             // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_SetBoolVariable;

// Function SandboxEngine.ModuleStateLuaAPI.SetNumberVariable
// 0x0018 (0x0018 - 0x0000)
struct ModuleStateLuaAPI_SetNumberVariable final
{
public:
	class FString                                 EventName;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Value;                                             // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_SetNumberVariable;

// Function SandboxEngine.ModuleStateLuaAPI.SetQuestCompletedForAllPlayers
// 0x0010 (0x0010 - 0x0000)
struct ModuleStateLuaAPI_SetQuestCompletedForAllPlayers final
{
public:
	class FString                                 String;                                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_SetQuestCompletedForAllPlayers;

// Function SandboxEngine.ModuleStateLuaAPI.SetQuestCompletedForAllPlayersOnTeam
// 0x0018 (0x0018 - 0x0000)
struct ModuleStateLuaAPI_SetQuestCompletedForAllPlayersOnTeam final
{
public:
	int32                                         TeamIndex;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 String;                                            // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_SetQuestCompletedForAllPlayersOnTeam;

// Function SandboxEngine.ModuleStateLuaAPI.SetStringVariable
// 0x0020 (0x0020 - 0x0000)
struct ModuleStateLuaAPI_SetStringVariable final
{
public:
	class FString                                 EventName;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 String;                                            // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_SetStringVariable;

// Function SandboxEngine.ModuleStateLuaAPI.SetTeamRoundsWon
// 0x0008 (0x0008 - 0x0000)
struct ModuleStateLuaAPI_SetTeamRoundsWon final
{
public:
	int32                                         TeamNum;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Rounds;                                            // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_SetTeamRoundsWon;

// Function SandboxEngine.ModuleStateLuaAPI.SetTeamScore
// 0x0008 (0x0008 - 0x0000)
struct ModuleStateLuaAPI_SetTeamScore final
{
public:
	int32                                         TeamNum;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Score;                                             // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ModuleStateLuaAPI_SetTeamScore;

// Function SandboxEngine.PrefabComponent.BeginComponent
// 0x0010 (0x0010 - 0x0000)
struct PrefabComponent_BeginComponent final
{
public:
	class FName                                   ComponentName;                                     // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ULE_ComponentGenerator*                 ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PrefabComponent_BeginComponent;

// Function SandboxEngine.PrefabComponent.BP_SetEditorAbsolutePosition
// 0x0018 (0x0018 - 0x0000)
struct PrefabComponent_BP_SetEditorAbsolutePosition final
{
public:
	struct FVector                                position;                                          // 0x0000(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PrefabComponent_BP_SetEditorAbsolutePosition;

// Function SandboxEngine.PrefabComponent.BP_SetEditorAbsoluteRotation
// 0x0020 (0x0020 - 0x0000)
struct PrefabComponent_BP_SetEditorAbsoluteRotation final
{
public:
	struct FQuat                                  Rotator;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PrefabComponent_BP_SetEditorAbsoluteRotation;

// Function SandboxEngine.PrefabComponent.BP_SetEditorAbsoluteScale
// 0x0018 (0x0018 - 0x0000)
struct PrefabComponent_BP_SetEditorAbsoluteScale final
{
public:
	struct FVector                                scale;                                             // 0x0000(0x0018)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PrefabComponent_BP_SetEditorAbsoluteScale;

// Function SandboxEngine.PrefabComponent.BP_SetEditorRelativePosition
// 0x0018 (0x0018 - 0x0000)
struct PrefabComponent_BP_SetEditorRelativePosition final
{
public:
	struct FVector                                position;                                          // 0x0000(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PrefabComponent_BP_SetEditorRelativePosition;

// Function SandboxEngine.PrefabComponent.BP_SetEditorRelativeRotation
// 0x0020 (0x0020 - 0x0000)
struct PrefabComponent_BP_SetEditorRelativeRotation final
{
public:
	struct FQuat                                  Rotator;                                           // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PrefabComponent_BP_SetEditorRelativeRotation;

// Function SandboxEngine.PrefabComponent.BP_SetEditorRelativeScale
// 0x0018 (0x0018 - 0x0000)
struct PrefabComponent_BP_SetEditorRelativeScale final
{
public:
	struct FVector                                scale;                                             // 0x0000(0x0018)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PrefabComponent_BP_SetEditorRelativeScale;

// Function SandboxEngine.PrefabFolder.FindOrMakeSubFolder
// 0x0018 (0x0018 - 0x0000)
struct PrefabFolder_FindOrMakeSubFolder final
{
public:
	class FString                                 Name_0;                                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UPrefabFolder*                          ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PrefabFolder_FindOrMakeSubFolder;

// Function SandboxEngine.TeamChangeButton.teamChange
// 0x0010 (0x0010 - 0x0000)
struct TeamChangeButton_teamChange final
{
public:
	class AActor*                                 OtherActor;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         TeamIndex;                                         // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TeamChangeButton_teamChange;

// Function SandboxEngine.TicketManager.AddToTicketHolders
// 0x0010 (0x0010 - 0x0000)
struct TicketManager_AddToTicketHolders final
{
public:
	TScriptInterface<class ITicketHolder>         Pawn;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TicketManager_AddToTicketHolders;

// Function SandboxEngine.TicketManager.AddToVerifiedTicketHolders
// 0x0010 (0x0010 - 0x0000)
struct TicketManager_AddToVerifiedTicketHolders final
{
public:
	TScriptInterface<class ITicketHolder>         Pawn;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TicketManager_AddToVerifiedTicketHolders;

// Function SandboxEngine.TicketManager.CheckOverlappingPawnTickets
// 0x0010 (0x0010 - 0x0000)
struct TicketManager_CheckOverlappingPawnTickets final
{
public:
	TScriptInterface<class ITicketHolder>         PawnToIgnore;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TicketManager_CheckOverlappingPawnTickets;

// Function SandboxEngine.TicketManager.CheckTicketSuccess
// 0x0028 (0x0028 - 0x0000)
struct TicketManager_CheckTicketSuccess final
{
public:
	TScriptInterface<class ITicketHolder>         Pawn;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         TeamIndex;                                         // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AModuleSlot*                            Slot;                                              // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSilent;                                           // 0x0020(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TicketManager_CheckTicketSuccess;

// Function SandboxEngine.TicketManager.CheckWhitelist
// 0x0020 (0x0020 - 0x0000)
struct TicketManager_CheckWhitelist final
{
public:
	int32                                         TeamIndex;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 PlayerName;                                        // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TicketManager_CheckWhitelist;

// Function SandboxEngine.TicketManager.CompareAndAdjustTeamColors
// 0x0038 (0x0038 - 0x0000)
struct TicketManager_CompareAndAdjustTeamColors final
{
public:
	struct FTeamColor                             CompareColor;                                      // 0x0000(0x001C)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	struct FTeamColor                             AdjustColor;                                       // 0x001C(0x001C)(Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TicketManager_CompareAndAdjustTeamColors;

// Function SandboxEngine.TicketManager.EmitStatEventForAllPlayers
// 0x0018 (0x0018 - 0x0000)
struct TicketManager_EmitStatEventForAllPlayers final
{
public:
	class FString                                 String;                                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         I;                                                 // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TicketManager_EmitStatEventForAllPlayers;

// Function SandboxEngine.TicketManager.EmitStatEventForAllPlayersOnTeam
// 0x0020 (0x0020 - 0x0000)
struct TicketManager_EmitStatEventForAllPlayersOnTeam final
{
public:
	int32                                         TeamIndex;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 String;                                            // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         I;                                                 // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TicketManager_EmitStatEventForAllPlayersOnTeam;

// Function SandboxEngine.TicketManager.GetMaxPlayerCount
// 0x0008 (0x0008 - 0x0000)
struct TicketManager_GetMaxPlayerCount final
{
public:
	int32                                         TeamIndex;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         ReturnValue;                                       // 0x0004(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TicketManager_GetMaxPlayerCount;

// Function SandboxEngine.TicketManager.GetTeamPlayerCount
// 0x0008 (0x0008 - 0x0000)
struct TicketManager_GetTeamPlayerCount final
{
public:
	int32                                         TeamIndex;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         ReturnValue;                                       // 0x0004(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TicketManager_GetTeamPlayerCount;

// Function SandboxEngine.TicketManager.GiveAndCheckTicket
// 0x0018 (0x0018 - 0x0000)
struct TicketManager_GiveAndCheckTicket final
{
public:
	TScriptInterface<class ITicketHolder>         Pawn;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         TeamIndex;                                         // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsSilent;                                         // 0x0014(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCheckOverlapping;                                 // 0x0015(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0016(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_17[0x1];                                       // 0x0017(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TicketManager_GiveAndCheckTicket;

// Function SandboxEngine.TicketManager.GiveTicket
// 0x0018 (0x0018 - 0x0000)
struct TicketManager_GiveTicket final
{
public:
	TScriptInterface<class ITicketHolder>         Pawn;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSilent;                                           // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0011(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TicketManager_GiveTicket;

// Function SandboxEngine.TicketManager.HandleClearTeam
// 0x0018 (0x0018 - 0x0000)
struct TicketManager_HandleClearTeam final
{
public:
	TScriptInterface<class ITicketHolder>         Pawn;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bResetCurrentTicket;                               // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSilent;                                           // 0x0011(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bPawnBeingDestroyed;                               // 0x0012(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bResetPawnCollision;                               // 0x0013(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0014(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TicketManager_HandleClearTeam;

// Function SandboxEngine.TicketManager.RemoveFromTicketHolders
// 0x0018 (0x0018 - 0x0000)
struct TicketManager_RemoveFromTicketHolders final
{
public:
	TScriptInterface<class ITicketHolder>         Pawn;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TicketManager_RemoveFromTicketHolders;

// Function SandboxEngine.TicketManager.RemovePawnFromVerifiedTicketHolders
// 0x0018 (0x0018 - 0x0000)
struct TicketManager_RemovePawnFromVerifiedTicketHolders final
{
public:
	TScriptInterface<class ITicketHolder>         Pawn;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TicketManager_RemovePawnFromVerifiedTicketHolders;

// Function SandboxEngine.TicketManager.RunTicketManagerTests
// 0x0001 (0x0001 - 0x0000)
struct TicketManager_RunTicketManagerTests final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TicketManager_RunTicketManagerTests;

// Function SandboxEngine.TicketManager.SetQuestCompletedForAllPlayers
// 0x0010 (0x0010 - 0x0000)
struct TicketManager_SetQuestCompletedForAllPlayers final
{
public:
	class FString                                 String;                                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TicketManager_SetQuestCompletedForAllPlayers;

// Function SandboxEngine.TicketManager.SetQuestCompletedForAllPlayersOnTeam
// 0x0018 (0x0018 - 0x0000)
struct TicketManager_SetQuestCompletedForAllPlayersOnTeam final
{
public:
	int32                                         TeamIndex;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 String;                                            // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TicketManager_SetQuestCompletedForAllPlayersOnTeam;

// Function SandboxEngine.TicketManager.SetTeamColors
// 0x003C (0x003C - 0x0000)
struct TicketManager_SetTeamColors final
{
public:
	struct FTeamColor                             HomeTeam;                                          // 0x0000(0x001C)(Parm, NoDestructor, NativeAccessSpecifierPublic)
	struct FTeamColor                             AwayTeam;                                          // 0x001C(0x001C)(Parm, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         TeamColorToPrioritize;                             // 0x0038(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_TicketManager_SetTeamColors;

// Function SandboxEngine.TicketManager.SetTicketVisuals
// 0x0001 (0x0001 - 0x0000)
struct TicketManager_SetTicketVisuals final
{
public:
	bool                                          bNewBool;                                          // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TicketManager_SetTicketVisuals;

// Function SandboxEngine.TicketManager.UpdateTicketSettings
// 0x0010 (0x0010 - 0x0000)
struct TicketManager_UpdateTicketSettings final
{
public:
	TArray<int32>                                 NewMaxTeamSizes;                                   // 0x0000(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_TicketManager_UpdateTicketSettings;

// Function SandboxEngine.LoadedGameMode.GetSlotID
// 0x0010 (0x0010 - 0x0000)
struct LoadedGameMode_GetSlotID final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_LoadedGameMode_GetSlotID;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
