#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TackleballScoreboard

#include "Basic.hpp"

#include "WBP_TackleballScoreboard_classes.hpp"
#include "WBP_TackleballScoreboard_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_TackleballScoreboard.WBP_TackleballScoreboard_C.AwayTeamScored
// (Event, Public, BlueprintEvent)

void UWBP_TackleballScoreboard_C::AwayTeamScored()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TackleballScoreboard_C", "AwayTeamScored");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TackleballScoreboard.WBP_TackleballScoreboard_C.BGOpenAnimationFinished
// (BlueprintCallable, BlueprintEvent)

void UWBP_TackleballScoreboard_C::BGOpenAnimationFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TackleballScoreboard_C", "BGOpenAnimationFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TackleballScoreboard.WBP_TackleballScoreboard_C.BGOpenAnimationStarted
// (BlueprintCallable, BlueprintEvent)

void UWBP_TackleballScoreboard_C::BGOpenAnimationStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TackleballScoreboard_C", "BGOpenAnimationStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TackleballScoreboard.WBP_TackleballScoreboard_C.ExecuteUbergraph_WBP_TackleballScoreboard
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TackleballScoreboard_C::ExecuteUbergraph_WBP_TackleballScoreboard(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TackleballScoreboard_C", "ExecuteUbergraph_WBP_TackleballScoreboard");

	Params::WBP_TackleballScoreboard_C_ExecuteUbergraph_WBP_TackleballScoreboard Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TackleballScoreboard.WBP_TackleballScoreboard_C.HomeTeamScored
// (Event, Public, BlueprintEvent)

void UWBP_TackleballScoreboard_C::HomeTeamScored()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TackleballScoreboard_C", "HomeTeamScored");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TackleballScoreboard.WBP_TackleballScoreboard_C.SequenceEvent__ENTRYPOINTWBP_TackleballScoreboard
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_TackleballScoreboard_C::SequenceEvent__ENTRYPOINTWBP_TackleballScoreboard()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TackleballScoreboard_C", "SequenceEvent__ENTRYPOINTWBP_TackleballScoreboard");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TackleballScoreboard.WBP_TackleballScoreboard_C.SequenceEvent__ENTRYPOINTWBP_TackleballScoreboard_0
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_TackleballScoreboard_C::SequenceEvent__ENTRYPOINTWBP_TackleballScoreboard_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TackleballScoreboard_C", "SequenceEvent__ENTRYPOINTWBP_TackleballScoreboard_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TackleballScoreboard.WBP_TackleballScoreboard_C.WidgetChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TackleballScoreboard_C::WidgetChanged(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TackleballScoreboard_C", "WidgetChanged");

	Params::WBP_TackleballScoreboard_C_WidgetChanged Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
