#!/usr/bin/env python3
r"""
make_rift.py - build the Rigel RIFT (PC) PUBLISH client from a stock A2 PC build.

Produces a folder that looks exactly like a normal shipping build (launcher + Engine + A2), pointed at
our backend, initialised under our own Meta app, and carrying the EOS station-browser redirect as an
ordinary-looking game binary. No UE4SS, no mods, no console.

WHAT IT CHANGES (and why each is done this way)

  1. Strip the mod tooling. The reference build (specnovbuild) shipped with UE4SS
     (A2\Binaries\Win64\dwmapi.dll proxy + ue4ss\ + Mods) and the IGCS camera tool
     (IGCS_ImGuiSettings.ini). A publish build must not carry any of it, so the copy drops those and
     any *.log.

  2. Dashboard / station API -- compile-time constant in A2-Win64-Shipping.exe.
        https://api.oriondrift.net  ->  https://rigel.wwiggles.org
     Patched IN PLACE, so both strings must be the same length. They are: 26 chars each.

  3. Mothership (login, user data) -- packaged BaseUrl. NOT patched (length-locked in the pak).
     Written to A2\Saved\Config\Windows\Engine.ini, which UE merges OVER the packaged DefaultEngine.ini.

  4. Oculus app identity -- RiftAppId in the same config override, set to OUR "spec"/publish Meta app
        1366120006579163
     THIS is what makes the entitlement check pass on its own: the signed-in account owns our app, so
     the Oculus platform grants the entitlement for real. Nothing is patched out. Keep it in step with
     MothershipServer.RIFT_APP_ID, which verifies the client's UserProof nonce under this app.

  5. EOS station browser -- the PC EOS SDK builds its backend host at runtime and talks to it through a
     statically-linked libcurl, so there is no config key to repoint (the [OnlineSubsystemEOS] BaseUrl
     below is written for completeness but the SDK ignores it). Instead we drop in eosredirect\dsound.dll
     -- a game binary that proxies the real dsound (which the exe imports by ordinal) and, at start-up,
     hooks curl_easy_setopt inside EOSSDK-Win64-Shipping.dll to rewrite epicgames.dev -> our gateway.
     See eosredirect\dllmain.cpp. Build it with eosredirect\build.ps1; this script only places it.

USAGE
    python make_rift.py --src ..\specnovbuild --dst ..\RiftPublish     # copy + strip + patch + config + dsound
    python make_rift.py --dst ..\RiftPublish --verify                  # re-check an existing folder
"""

import argparse
import os
import shutil
import sys

DASHBOARD_OLD  = b"https://api.oriondrift.net"
DASHBOARD_NEW  = b"https://rigel.wwiggles.org"
MOTHERSHIP_URL = "https://rigel-ms.wwiggles.org"
EOS_URL        = "https://rigel-eos.wwiggles.org"
# Our own "spec"/publish Meta app for the PC/Rift build. Initialising under it is what makes the
# entitlement check PASS legitimately. Must stay in step with MothershipServer.RIFT_APP_ID.
RIFT_APP_ID    = "1366120006579163"

# Mod tooling that must never be in a publish build.
STRIP_FILES = {"dwmapi.dll", "igcs_imguisettings.ini"}
STRIP_DIRS  = {"ue4ss"}
STRIP_EXT   = {".log"}

ENGINE_INI = f"""; Rigel Rift (PC) publish build - backend + app identity. Generated by make_rift.py.
; UE merges this USER config OVER the packaged A2/Config/DefaultEngine.ini, and a key set here wins.

[OnlineSubsystemOculus]
RiftAppId={RIFT_APP_ID}

[OnlineSubsystemMothership]
BaseUrl="{MOTHERSHIP_URL}"

[OnlineSubsystemEOS]
BaseUrl="{EOS_URL}"
"""


def exe_path(dst):
    return os.path.join(dst, "A2", "Binaries", "Win64", "A2-Win64-Shipping.exe")


def dsound_src():
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), "eosredirect", "dsound.dll")


def copy_stripped(src, dst):
    if not os.path.isdir(src):
        sys.exit(f"source build not found: {src}")
    print(f"copying {src} -> {dst}, dropping mod tooling (this is a few GB)")
    stripped = []

    def ignore(dirpath, names):
        drop = set()
        for n in names:
            low = n.lower()
            full = os.path.join(dirpath, n)
            if low in STRIP_FILES or os.path.splitext(low)[1] in STRIP_EXT:
                drop.add(n); stripped.append(full)
            elif os.path.isdir(full) and low in STRIP_DIRS:
                drop.add(n); stripped.append(full + "\\")
        return drop

    shutil.copytree(src, dst, dirs_exist_ok=True, ignore=ignore)
    print("  copy complete; stripped:")
    for s in stripped:
        print("    -", os.path.relpath(s, dst))


def patch_dashboard(dst):
    exe = exe_path(dst)
    blob = open(exe, "rb").read()
    if blob.count(DASHBOARD_NEW):
        print(f"  dashboard URL: already {DASHBOARD_NEW.decode()}")
        return True
    n = blob.count(DASHBOARD_OLD)
    if n != 1:
        print(f"  dashboard URL: expected 1 occurrence of {DASHBOARD_OLD.decode()}, found {n}")
        return False
    assert len(DASHBOARD_OLD) == len(DASHBOARD_NEW)
    at = blob.find(DASHBOARD_OLD)
    with open(exe, "r+b") as f:
        f.seek(at); f.write(DASHBOARD_NEW)
    print(f"  dashboard URL: patched at 0x{at:X} -> {DASHBOARD_NEW.decode()}")
    return True


def write_config(dst):
    cfg_dir = os.path.join(dst, "A2", "Saved", "Config", "Windows")
    os.makedirs(cfg_dir, exist_ok=True)
    path = os.path.join(cfg_dir, "Engine.ini")
    with open(path, "w", encoding="utf-8") as f:
        f.write(ENGINE_INI)
    print(f"  config override: {path}")


def place_dsound(dst):
    src = dsound_src()
    if not os.path.exists(src):
        print(f"  dsound.dll: NOT FOUND at {src} -- build it with eosredirect\\build.ps1 first")
        return False
    dstf = os.path.join(dst, "A2", "Binaries", "Win64", "dsound.dll")
    shutil.copyfile(src, dstf)
    print(f"  EOS redirect: placed dsound.dll ({os.path.getsize(dstf)} bytes)")
    return True


def verify(dst):
    ok = True
    exe = exe_path(dst)
    blob = open(exe, "rb").read()
    if blob.count(DASHBOARD_NEW) == 1 and blob.count(DASHBOARD_OLD) == 0:
        print(f"  OK  dashboard -> {DASHBOARD_NEW.decode()}")
    else:
        ok = False; print(f"  BAD dashboard: new={blob.count(DASHBOARD_NEW)} old={blob.count(DASHBOARD_OLD)}")

    cfg = os.path.join(dst, "A2", "Saved", "Config", "Windows", "Engine.ini")
    ctext = open(cfg, encoding="utf-8").read() if os.path.exists(cfg) else ""
    print(f"  {'OK ' if MOTHERSHIP_URL in ctext else 'BAD'} mothership override")
    print(f"  {'OK ' if f'RiftAppId={RIFT_APP_ID}' in ctext else 'BAD'} RiftAppId={RIFT_APP_ID}")
    if MOTHERSHIP_URL not in ctext or f"RiftAppId={RIFT_APP_ID}" not in ctext: ok = False

    dstf = os.path.join(dst, "A2", "Binaries", "Win64", "dsound.dll")
    print(f"  {'OK ' if os.path.exists(dstf) else 'BAD'} EOS redirect dsound.dll present")
    if not os.path.exists(dstf): ok = False

    # No mod tooling left behind.
    leftover = []
    for root, dirs, files in os.walk(dst):
        for d in list(dirs):
            if d.lower() in STRIP_DIRS: leftover.append(os.path.join(root, d))
        for fn in files:
            if fn.lower() in STRIP_FILES: leftover.append(os.path.join(root, fn))
    if leftover:
        ok = False; print("  BAD mod tooling still present:")
        for l in leftover: print("      ", os.path.relpath(l, dst))
    else:
        print("  OK  no UE4SS / IGCS / dwmapi tooling in the build")
    return ok


def main():
    ap = argparse.ArgumentParser(description="Build the Rigel Rift (PC) publish client")
    ap.add_argument("--src", help="stock PC build to copy from (e.g. ..\\specnovbuild)")
    ap.add_argument("--dst", default="..\\RiftPublish", help="output build folder")
    ap.add_argument("--verify", action="store_true", help="only re-check an existing folder")
    args = ap.parse_args()

    if args.verify:
        sys.exit(0 if verify(args.dst) else 1)

    if args.src:
        copy_stripped(args.src, args.dst)
    if not os.path.exists(exe_path(args.dst)):
        sys.exit(f"no build at {args.dst} -- pass --src to copy one first")

    print("redirecting backend + identity")
    patch_dashboard(args.dst)
    write_config(args.dst)
    place_dsound(args.dst)
    print("\nstate:")
    verify(args.dst)


if __name__ == "__main__":
    main()
